package cn.blockeco.exchange.application;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import cn.blockeco.exchange.domain.company.CompanyId;
import cn.blockeco.exchange.domain.money.Money;
import cn.blockeco.exchange.infrastructure.sql.Database;
import cn.blockeco.exchange.infrastructure.sql.SqlPrimaryOfferingRepository;
import cn.blockeco.exchange.ports.AppClock;
import cn.blockeco.exchange.ports.EconomyGateway;
import cn.blockeco.exchange.ports.TreasuryEscrowGateway;
import java.nio.file.*;
import java.time.*;
import java.util.UUID;
import cn.blockeco.exchange.domain.finance.*;
import org.junit.jupiter.api.Test;

class PrimaryOfferingServiceTest {
 @Test void first_subscription_opens_announced_offering_in_its_transaction_before_money_moves() throws Exception {
  Path file=Files.createTempFile("ipo-sub-open-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); CompanyId c=Fixtures.company(db,100); UUID founder=Fixtures.founder(db,c); Fixtures.activeAsset(db,c,founder); MutableClock clock=new MutableClock(); SqlPrimaryOfferingRepository repo=new SqlPrimaryOfferingRepository(db.dataSource()); PrimaryOfferingService service=new PrimaryOfferingService(repo,db,new Escrow(),Runnable::run,clock); var offer=service.announce(c,founder,Money.ofMinor(100),Money.ofMinor(10)).toCompletableFuture().join(); clock.now=offer.opensAt(); service.subscribe(UUID.randomUUID(),offer.id(),1).toCompletableFuture().join(); assertThat(repo.find(offer.id()).orElseThrow().state()).isEqualTo(cn.blockeco.exchange.domain.finance.PrimaryOfferingState.OPEN); assertThat(auditCount(db,offer.id(),"OPEN")).isEqualTo(1); }finally{Files.deleteIfExists(file);} }
 @Test void never_replays_a_persisted_prepared_subscription_after_a_crash_window() throws Exception {
  Path file=Files.createTempFile("ipo-recovery-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)) { db.migrate(); CompanyId c=Fixtures.company(db,100); MutableClock clock=new MutableClock(); SqlPrimaryOfferingRepository repo=new SqlPrimaryOfferingRepository(db.dataSource()); UUID founder=Fixtures.founder(db,c);
   Fixtures.activeAsset(db,c,founder); PrimaryOfferingService service=new PrimaryOfferingService(repo,db,new Escrow(),Runnable::run,clock);
   var offer=service.announce(c,founder,Money.ofMinor(100),Money.ofMinor(10)).toCompletableFuture().join(); clock.now=offer.opensAt(); UUID subscriber=UUID.randomUUID(); UUID subscription=UUID.nameUUIDFromBytes((offer.id()+":"+subscriber+":2").getBytes(java.nio.charset.StandardCharsets.UTF_8));
   db.inTransaction(x->{repo.prepareSubscription(x,subscription,offer,subscriber,2,clock.now);return null;});
   assertThat(service.subscribe(subscriber,offer.id(),2).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.RECOVERY_REQUIRED);
  } finally {Files.deleteIfExists(file);} }
 @Test void requires_active_asset_caps_target_and_honors_exact_open_close_boundaries() throws Exception {
  Path file=Files.createTempFile("ipo-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)) { db.migrate(); CompanyId c=Fixtures.company(db,100_000); UUID founder=Fixtures.founder(db,c); MutableClock clock=new MutableClock();
   PrimaryOfferingService service=new PrimaryOfferingService(new SqlPrimaryOfferingRepository(db.dataSource()), db, new Escrow(), Runnable::run, clock);
   assertThatThrownBy(()->service.announce(c,founder,Money.ofMinor(1),Money.ofMinor(1)).toCompletableFuture().join()).hasCauseInstanceOf(IllegalStateException.class);
   Fixtures.activeAsset(db,c,founder);
   assertThatThrownBy(()->service.announce(c,founder,Money.ofMinor(500_001),Money.ofMinor(1)).toCompletableFuture().join()).hasCauseInstanceOf(IllegalArgumentException.class);
   var offer=service.announce(c,founder,Money.ofMinor(500_000),Money.ofMinor(100)).toCompletableFuture().join(); UUID buyer=UUID.randomUUID();
   assertThat(service.subscribe(buyer,offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.NOT_OPEN);
   clock.now=offer.opensAt(); service.subscribe(buyer,offer.id(),2).toCompletableFuture().join();
   clock.now=offer.closesAt(); assertThat(service.subscribe(UUID.randomUUID(),offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.NOT_OPEN);
  } finally {Files.deleteIfExists(file);} }
 @Test void subscription_does_not_list_company_until_the_offering_closes() throws Exception {
  Path file=Files.createTempFile("ipo-list-on-close-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)) { db.migrate(); CompanyId c=Fixtures.company(db,100); UUID founder=Fixtures.founder(db,c); Fixtures.activeAsset(db,c,founder); MutableClock clock=new MutableClock(); SqlPrimaryOfferingRepository repo=new SqlPrimaryOfferingRepository(db.dataSource()); PrimaryOfferingService service=new PrimaryOfferingService(repo,db,new Escrow(),Runnable::run,clock);
   var offer=service.announce(c,founder,Money.ofMinor(100),Money.ofMinor(10)).toCompletableFuture().join(); clock.now=offer.opensAt(); service.subscribe(UUID.randomUUID(),offer.id(),1).toCompletableFuture().join();
   assertThat(companyStatus(db,c)).isEqualTo("PENDING_ASSET_BINDING");
   clock.now=offer.closesAt(); service.closeExpired(clock.now).toCompletableFuture().join();
   assertThat(companyStatus(db,c)).isEqualTo("LISTED");
  } finally {Files.deleteIfExists(file);} }
 @Test void escrowed_subscription_completed_after_expiry_lists_once_even_when_scheduler_saw_zero_completed_shares() throws Exception {
  Path file=Files.createTempFile("ipo-expiry-completion-race-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)) { db.migrate(); CompanyId c=Fixtures.company(db,100); UUID founder=Fixtures.founder(db,c); Fixtures.activeAsset(db,c,founder); MutableClock clock=new MutableClock(); SqlPrimaryOfferingRepository repo=new SqlPrimaryOfferingRepository(db.dataSource()); PrimaryOfferingService service=new PrimaryOfferingService(repo,db,new Escrow(),Runnable::run,clock);
   var offer=service.announce(c,founder,Money.ofMinor(100),Money.ofMinor(10)).toCompletableFuture().join(); UUID subscriber=UUID.randomUUID(); UUID subscription=UUID.nameUUIDFromBytes((offer.id()+":"+subscriber+":1").getBytes(java.nio.charset.StandardCharsets.UTF_8)); clock.now=offer.opensAt(); db.inTransaction(x->{repo.prepareSubscription(x,subscription,offer,subscriber,1,clock.now);repo.markWithdrawn(x,subscription,clock.now);repo.markEscrowDeposited(x,subscription,clock.now);return null;});
   clock.now=offer.closesAt(); service.closeExpired(clock.now).toCompletableFuture().join(); assertThat(companyStatus(db,c)).isEqualTo("PENDING_ASSET_BINDING"); assertThat(ipoListedAuditCount(db,offer.id())).isZero();
   db.inTransaction(x->{repo.completeSubscription(x,subscription,clock.now);repo.completeSubscription(x,subscription,clock.now);return null;}); service.closeExpired(clock.now).toCompletableFuture().join();
   assertThat(companyStatus(db,c)).isEqualTo("LISTED"); assertThat(ipoListedAuditCount(db,offer.id())).isEqualTo(1);
  } finally {Files.deleteIfExists(file);} }
 @Test void sold_out_is_a_typed_result_and_does_not_call_vault_for_the_rejected_buyer() throws Exception {
  Path file=Files.createTempFile("ipo-sold-out-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)) { db.migrate(); CompanyId c=Fixtures.company(db,100); UUID founder=Fixtures.founder(db,c); Fixtures.activeAsset(db,c,founder); MutableClock clock=new MutableClock(); SqlPrimaryOfferingRepository repo=new SqlPrimaryOfferingRepository(db.dataSource()); CountingEscrow escrow=new CountingEscrow(); PrimaryOfferingService service=new PrimaryOfferingService(repo,db,escrow,Runnable::run,clock);
   var offer=service.announce(c,founder,Money.ofMinor(10),Money.ofMinor(10)).toCompletableFuture().join(); clock.now=offer.opensAt();
   assertThat(service.subscribe(UUID.randomUUID(),offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.SUCCESS);
   assertThat(service.subscribe(UUID.randomUUID(),offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.SOLD_OUT);
   assertThat(escrow.withdrawCalls).isEqualTo(1);
  } finally {Files.deleteIfExists(file);} }
 @Test void persisted_withdrawn_or_escrow_deposited_subscription_never_replays_vault() throws Exception {
  Path file=Files.createTempFile("ipo-no-replay-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); CompanyId c=Fixtures.company(db,100); UUID founder=Fixtures.founder(db,c); Fixtures.activeAsset(db,c,founder); MutableClock clock=new MutableClock(); SqlPrimaryOfferingRepository repo=new SqlPrimaryOfferingRepository(db.dataSource()); CountingEscrow escrow=new CountingEscrow(); PrimaryOfferingService service=new PrimaryOfferingService(repo,db,escrow,Runnable::run,clock); var offer=service.announce(c,founder,Money.ofMinor(100),Money.ofMinor(10)).toCompletableFuture().join(); clock.now=offer.opensAt(); UUID buyer=UUID.randomUUID(); UUID id=UUID.nameUUIDFromBytes((offer.id()+":"+buyer+":1").getBytes(java.nio.charset.StandardCharsets.UTF_8)); db.inTransaction(tx->{repo.prepareSubscription(tx,id,offer,buyer,1,clock.now);repo.markWithdrawn(tx,id,clock.now);return null;});
   assertThat(service.subscribe(buyer,offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.RECOVERY_REQUIRED); assertThat(escrow.withdrawCalls).isZero();
  }finally{Files.deleteIfExists(file);} }
 @Test void withdrawal_exception_marks_real_subscription_ambiguous_once() throws Exception { withScenario((db,repo,offer,buyer,clock,gateway)->{gateway.throwWithdraw=true; PrimaryOfferingService service=new PrimaryOfferingService(repo,db,gateway,Runnable::run,clock); assertThat(service.subscribe(buyer,offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.RECOVERY_REQUIRED); assertAmbiguous(db,offer,buyer); assertThat(gateway.withdrawCalls).isEqualTo(1);assertThat(gateway.depositCalls).isZero();}); }
 @Test void withdrawal_state_transaction_rollback_marks_prepared_subscription_ambiguous_once() throws Exception { withScenario((db,repo,offer,buyer,clock,gateway)->{PrimaryOfferingService service=new PrimaryOfferingService(repo,new FailingTransactions(db,2),gateway,Runnable::run,clock); assertThat(service.subscribe(buyer,offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.RECOVERY_REQUIRED); assertAmbiguous(db,offer,buyer); assertThat(gateway.withdrawCalls).isEqualTo(1);assertThat(gateway.depositCalls).isZero();}); }
 @Test void deposit_exception_and_failure_mark_withdrawn_subscription_ambiguous_once() throws Exception { withScenario((db,repo,offer,buyer,clock,gateway)->{gateway.throwDeposit=true; PrimaryOfferingService service=new PrimaryOfferingService(repo,db,gateway,Runnable::run,clock); assertThat(service.subscribe(buyer,offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.RECOVERY_REQUIRED); assertAmbiguous(db,offer,buyer); assertThat(gateway.withdrawCalls).isEqualTo(1);assertThat(gateway.depositCalls).isEqualTo(1);}); }
 @Test void deposit_failure_outcome_marks_withdrawn_subscription_ambiguous_once() throws Exception { withScenario((db,repo,offer,buyer,clock,gateway)->{gateway.depositResult=EconomyGateway.Result.providerFailure("down"); PrimaryOfferingService service=new PrimaryOfferingService(repo,db,gateway,Runnable::run,clock); assertThat(service.subscribe(buyer,offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.RECOVERY_REQUIRED); assertAmbiguous(db,offer,buyer); assertThat(gateway.withdrawCalls).isEqualTo(1);assertThat(gateway.depositCalls).isEqualTo(1);}); }
 @Test void final_transaction_rollback_leaves_no_issued_cash_holding_or_shares_and_marks_ambiguous() throws Exception { withScenario((db,repo,offer,buyer,clock,gateway)->{CompanyId company=offer.companyId(); long cash=cash(db,company), shares=repo.companyTotalShares(company); PrimaryOfferingService service=new PrimaryOfferingService(repo,new FailingTransactions(db,3),gateway,Runnable::run,clock); assertThat(service.subscribe(buyer,offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.RECOVERY_REQUIRED); assertAmbiguous(db,offer,buyer); assertThat(cash(db,company)).isEqualTo(cash);assertThat(repo.companyTotalShares(company)).isEqualTo(shares);assertThat(holding(db,company,buyer)).isZero();assertThat(gateway.withdrawCalls).isEqualTo(1);assertThat(gateway.depositCalls).isEqualTo(1);}); }
 @Test void insufficient_with_cancel_transaction_failure_marks_prepared_subscription_ambiguous_once() throws Exception { withScenario((db,repo,offer,buyer,clock,gateway)->{gateway.withdrawResult=EconomyGateway.Result.insufficientFunds("no"); PrimaryOfferingService service=new PrimaryOfferingService(repo,new FailingTransactions(db,2),gateway,Runnable::run,clock); assertThat(service.subscribe(buyer,offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.RECOVERY_REQUIRED); assertAmbiguous(db,offer,buyer); assertThat(gateway.withdrawCalls).isEqualTo(1);assertThat(gateway.depositCalls).isZero();}); }
 @Test void persisted_escrow_deposited_subscription_returns_recovery_without_vault_or_share_issue() throws Exception { withScenario((db,repo,offer,buyer,clock,gateway)->{UUID id=subscriptionId(offer,buyer,1);db.inTransaction(c->{repo.prepareSubscription(c,id,offer,buyer,1,clock.now);repo.markWithdrawn(c,id,clock.now);repo.markEscrowDeposited(c,id,clock.now);return null;});long cash=cash(db,offer.companyId()),shares=repo.companyTotalShares(offer.companyId());PrimaryOfferingService service=new PrimaryOfferingService(repo,db,gateway,Runnable::run,clock);assertThat(service.subscribe(buyer,offer.id(),1).toCompletableFuture().join().status()).isEqualTo(SubscriptionResult.Status.RECOVERY_REQUIRED);assertThat(operationState(db,id)).isEqualTo("ESCROW_DEPOSITED");assertThat(gateway.withdrawCalls).isZero();assertThat(gateway.depositCalls).isZero();assertThat(cash(db,offer.companyId())).isEqualTo(cash);assertThat(repo.companyTotalShares(offer.companyId())).isEqualTo(shares);assertThat(holding(db,offer.companyId(),buyer)).isZero();}); }
 private static String companyStatus(Database db,CompanyId company){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT status FROM companies WHERE id=?")){s.setString(1,company.value().toString());try(var r=s.executeQuery()){r.next();return r.getString(1);}}catch(Exception e){throw new RuntimeException(e);}}
 private static long ipoListedAuditCount(Database db,UUID offering){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT COUNT(*) FROM audit_events WHERE event_type='IPO_LISTED' AND payload_json LIKE ?")){s.setString(1,"%"+offering+"%");try(var r=s.executeQuery()){r.next();return r.getLong(1);}}catch(Exception e){throw new RuntimeException(e);}}
 static final class MutableClock implements AppClock { Instant now=Instant.parse("2026-08-14T12:00:00Z"); public Instant now(){return now;} }
 static class Escrow implements TreasuryEscrowGateway { public EconomyGateway.Result withdrawPlayer(UUID p,Money m,UUID i){return EconomyGateway.Result.success("");} public EconomyGateway.Result depositEscrow(Money m,UUID i){return EconomyGateway.Result.success("");} public EconomyGateway.Result withdrawEscrow(Money m,UUID i){return EconomyGateway.Result.success("");} public EconomyGateway.Result refundPlayer(UUID p,Money m,UUID i){return EconomyGateway.Result.success("");} }
 static class CountingEscrow extends Escrow { int withdrawCalls; @Override public EconomyGateway.Result withdrawPlayer(UUID p,Money m,UUID i){withdrawCalls++;return super.withdrawPlayer(p,m,i);} }
 static final class ProgrammableEscrow extends Escrow { int withdrawCalls,depositCalls; boolean throwWithdraw,throwDeposit; EconomyGateway.Result withdrawResult=EconomyGateway.Result.success("");EconomyGateway.Result depositResult=EconomyGateway.Result.success(""); @Override public EconomyGateway.Result withdrawPlayer(UUID p,Money m,UUID i){withdrawCalls++;if(throwWithdraw)throw new IllegalStateException("withdraw failed");return withdrawResult;}@Override public EconomyGateway.Result depositEscrow(Money m,UUID i){depositCalls++;if(throwDeposit)throw new IllegalStateException("deposit failed");return depositResult;} }
 static final class FailingTransactions implements cn.blockeco.exchange.ports.TransactionRunner { private final Database db;private final int failCall;private int calls; FailingTransactions(Database db,int failCall){this.db=db;this.failCall=failCall;}public <T>T inTransaction(SqlWork<T> work){int call=++calls;return db.inTransaction(c->{T result=work.execute(c);if(call==failCall)throw new IllegalStateException("injected rollback");return result;});} }
 @FunctionalInterface interface Scenario {void run(Database db,SqlPrimaryOfferingRepository repo,PrimaryOffering offer,UUID buyer,MutableClock clock,ProgrammableEscrow gateway)throws Exception;}
 private static void withScenario(Scenario scenario)throws Exception{Path file=Files.createTempFile("ipo-failure-", ".db");try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate();CompanyId company=Fixtures.company(db,100);UUID founder=Fixtures.founder(db,company);Fixtures.activeAsset(db,company,founder);MutableClock clock=new MutableClock();SqlPrimaryOfferingRepository repo=new SqlPrimaryOfferingRepository(db.dataSource());PrimaryOffering offer=new PrimaryOfferingService(repo,db,new Escrow(),Runnable::run,clock).announce(company,founder,Money.ofMinor(100),Money.ofMinor(10)).toCompletableFuture().join();clock.now=offer.opensAt();scenario.run(db,repo,offer,UUID.randomUUID(),clock,new ProgrammableEscrow());}finally{Files.deleteIfExists(file);}}
 private static UUID subscriptionId(PrimaryOffering offer,UUID buyer,long shares){return UUID.nameUUIDFromBytes((offer.id()+":"+buyer+":"+shares).getBytes(java.nio.charset.StandardCharsets.UTF_8));}
 private static void assertAmbiguous(Database db,PrimaryOffering offer,UUID buyer){UUID id=subscriptionId(offer,buyer,1);assertThat(operationState(db,id)).isEqualTo("AMBIGUOUS");assertThat(auditEvents(db,id,"IPO_TREASURY_AMBIGUOUS")).isEqualTo(1);}
 private static String operationState(Database db,UUID id){return string(db,"SELECT state FROM treasury_operations WHERE id=?",id.toString());}private static long cash(Database db,CompanyId company){return number(db,"SELECT cash_minor FROM company_cash_accounts WHERE company_id=?",company.value().toString());}private static long holding(Database db,CompanyId company,UUID player){return number(db,"SELECT COALESCE((SELECT available_shares FROM share_holdings WHERE company_id=? AND holder_uuid=?),0)",company.value().toString(),player.toString());}private static long auditEvents(Database db,UUID id,String event){return number(db,"SELECT COUNT(*) FROM audit_events WHERE event_type=? AND payload_json LIKE ?",event,"%"+id+"%");}private static long number(Database db,String sql,String...values){try(var c=db.dataSource().getConnection();var s=c.prepareStatement(sql)){for(int i=0;i<values.length;i++)s.setString(i+1,values[i]);try(var r=s.executeQuery()){r.next();return r.getLong(1);}}catch(Exception e){throw new RuntimeException(e);}}private static String string(Database db,String sql,String value){try(var c=db.dataSource().getConnection();var s=c.prepareStatement(sql)){s.setString(1,value);try(var r=s.executeQuery()){r.next();return r.getString(1);}}catch(Exception e){throw new RuntimeException(e);}}
 static long auditCount(Database db,UUID offering,String to){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT COUNT(*) FROM audit_events WHERE event_type='IPO_STATE_CHANGED' AND payload_json LIKE ? AND payload_json LIKE ?")){s.setString(1,"%"+offering+"%");s.setString(2,"%\"to\":\""+to+"\"%");try(var r=s.executeQuery()){r.next();return r.getLong(1);}}catch(Exception e){throw new RuntimeException(e);}}
}
