package cn.blockeco.exchange.infrastructure.sql;

import cn.blockeco.exchange.domain.company.CompanyId;
import cn.blockeco.exchange.domain.audit.AuditEvent;
import cn.blockeco.exchange.domain.finance.*;
import cn.blockeco.exchange.domain.money.Money;
import cn.blockeco.exchange.ports.PrimaryOfferingRepository;
import cn.blockeco.exchange.application.IpoSubscriptionRecoveryRecord;
import cn.blockeco.exchange.application.IpoSubscriptionRecoverySummary;
import java.sql.*; import java.time.Instant; import java.util.*; import javax.sql.DataSource;

public final class SqlPrimaryOfferingRepository implements PrimaryOfferingRepository {
 private final DataSource ds; private final SqlAuditLog audits=new SqlAuditLog(); public SqlPrimaryOfferingRepository(DataSource ds){this.ds=ds;}
 public void announce(Connection c,PrimaryOffering o)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO primary_offerings VALUES (?,?,?,?,?,?,?,?,?)")){s.setString(1,o.id().toString());s.setString(2,o.companyId().value().toString());s.setLong(3,o.target().minorUnits());s.setLong(4,o.issuePrice().minorUnits());s.setLong(5,o.maximumShares());s.setString(6,o.announcedAt().toString());s.setString(7,o.opensAt().toString());s.setString(8,o.closesAt().toString());s.setString(9,o.state().name());s.executeUpdate();} announcement(c,o,"首次公开发行公告：认购编号="+o.id()+"；目标="+o.target().minorUnits()+"；发行价="+o.issuePrice().minorUnits()+"；最大股数="+o.maximumShares()+"；开放="+o.opensAt()+"；结束="+o.closesAt()+"；实缴资本="+number(c,"SELECT paid_in_capital_minor FROM company_cash_accounts WHERE company_id=?",o.companyId().value().toString())+"；风险提示：股票价格可能波动，投资有风险，不承诺收益。");audit(c,o.companyId(),null,"IPO_ANNOUNCED",Map.of("offeringId",o.id().toString(),"targetMinor",o.target().minorUnits(),"issuePriceMinor",o.issuePrice().minorUnits()),o.announcedAt());}
 public Optional<PrimaryOffering> find(UUID id){try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement("SELECT * FROM primary_offerings WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(offer(r)):Optional.empty();}}catch(SQLException e){throw new IllegalStateException("could not find offering",e);}}
 public List<PublicOfferingView> listPublic(int limit){int bounded=Math.max(1,Math.min(50,limit));try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(publicOfferingSql()+" GROUP BY po.id ORDER BY po.announced_at DESC, po.id DESC LIMIT ?")){s.setInt(1,bounded);try(ResultSet r=s.executeQuery()){List<PublicOfferingView> result=new ArrayList<>();while(r.next())result.add(publicOffer(r));return List.copyOf(result);}}catch(SQLException e){throw new IllegalStateException("could not list public offerings",e);}}
 public Optional<PublicOfferingView> findPublic(UUID id){try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(publicOfferingSql()+" AND po.id=? GROUP BY po.id")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(publicOffer(r)):Optional.empty();}}catch(SQLException e){throw new IllegalStateException("could not find public offering",e);}}
 public long paidInCapital(CompanyId id){return number("SELECT paid_in_capital_minor FROM company_cash_accounts WHERE company_id=?",id.value().toString());}
 public boolean hasActiveAsset(CompanyId id){return number("SELECT COUNT(*) FROM asset_bindings WHERE company_id=? AND state='ACTIVE'",id.value().toString())>0;}
 public boolean isFounder(CompanyId id,UUID founder){return number("SELECT COUNT(*) FROM companies WHERE id=? AND founder_uuid=?",id.value().toString(),founder.toString())==1;}
 public SubscriptionPreparation prepareSubscription(Connection c,UUID id,PrimaryOffering o,UUID subscriber,long shares,Instant now)throws SQLException{ Optional<TreasuryOperation> existing=findOperation(c,id); if(existing.isPresent()) return new SubscriptionPreparation(existing.get(),false); if(shares<=0)throw rejected(SubscriptionPreparationRejection.INVALID,"shares must be positive"); long issued=number(c,"SELECT COALESCE(SUM(ps.shares),0) FROM primary_subscriptions ps JOIN treasury_operations t ON t.id=ps.id WHERE ps.offering_id=? AND t.state<>'REFUNDED'",o.id().toString()); if(shares>o.maximumShares()-issued)throw rejected(SubscriptionPreparationRejection.SOLD_OUT,"insufficient offering shares"); ensureOpen(c,o.id(),now); long amount;try{amount=Math.multiplyExact(shares,o.issuePrice().minorUnits());}catch(ArithmeticException overflow){throw rejected(SubscriptionPreparationRejection.INVALID,"subscription amount overflow",overflow);} try(PreparedStatement s=c.prepareStatement("INSERT INTO primary_subscriptions VALUES (?,?,?,?,?,?,?,?)")){s.setString(1,id.toString());s.setString(2,o.id().toString());s.setString(3,o.companyId().value().toString());s.setString(4,subscriber.toString());s.setLong(5,shares);s.setLong(6,amount);s.setString(7,id.toString());s.setString(8,now.toString());s.executeUpdate();} try(PreparedStatement s=c.prepareStatement("INSERT INTO treasury_operations VALUES (?,?,?,?,?,?,?,?)")){s.setString(1,id.toString());s.setString(2,o.companyId().value().toString());s.setString(3,subscriber.toString());s.setLong(4,amount);s.setString(5,id.toString());s.setString(6,"PREPARED");s.setString(7,now.toString());s.setString(8,now.toString());s.executeUpdate();} return new SubscriptionPreparation(new TreasuryOperation(id,o.companyId(),subscriber,Money.ofMinor(amount),id.toString(),TreasuryOperationState.PREPARED,now,now),true); }
 public void markWithdrawn(Connection c,UUID id,Instant now)throws SQLException{transition(c,id,"PREPARED","PLAYER_WITHDRAWN",now);} public void markEscrowDeposited(Connection c,UUID id,Instant now)throws SQLException{transition(c,id,"PLAYER_WITHDRAWN","ESCROW_DEPOSITED",now);} public void markAmbiguous(Connection c,UUID id,String stage,String reason,Instant now)throws SQLException{TreasuryOperation op=operation(c,id);if(op.state()==TreasuryOperationState.AMBIGUOUS||op.state()==TreasuryOperationState.COMPLETED||op.state()==TreasuryOperationState.REFUNDED)return;String actual=op.state().name();if(op.state()!=TreasuryOperationState.PREPARED&&op.state()!=TreasuryOperationState.PLAYER_WITHDRAWN&&op.state()!=TreasuryOperationState.ESCROW_DEPOSITED)return;try(PreparedStatement s=c.prepareStatement("UPDATE treasury_operations SET state='AMBIGUOUS',updated_at=? WHERE id=? AND state=?")){s.setString(1,now.toString());s.setString(2,id.toString());s.setString(3,actual);if(s.executeUpdate()==1)audit(c,op.companyId(),op.playerId(),"IPO_TREASURY_AMBIGUOUS",Map.of("subscriptionId",id.toString(),"actualState",actual,"externalStage",stage,"reason",reason),now);}}
 public void cancelPrepared(Connection c,UUID id,Instant now)throws SQLException{transition(c,id,"PREPARED","REFUNDED",now);}
 public void completeSubscription(Connection c,UUID id,Instant now)throws SQLException{ TreasuryOperation op=operation(c,id); if(op.state()==TreasuryOperationState.COMPLETED)return; if(op.state()!=TreasuryOperationState.ESCROW_DEPOSITED)throw new IllegalStateException("subscription requires recovery"); UUID offering=offeringId(c,id); long shares=number(c,"SELECT shares FROM primary_subscriptions WHERE id=?",id.toString()); try(PreparedStatement s=c.prepareStatement("UPDATE company_cash_accounts SET cash_minor=cash_minor+? WHERE company_id=?")){s.setLong(1,op.amount().minorUnits());s.setString(2,op.companyId().value().toString());if(s.executeUpdate()!=1)throw new IllegalStateException("cash account missing");} try(PreparedStatement s=c.prepareStatement("INSERT INTO share_holdings (company_id,holder_uuid,available_shares,reserved_shares) VALUES (?,?,?,0) ON CONFLICT(company_id,holder_uuid) DO UPDATE SET available_shares=available_shares+excluded.available_shares")){s.setString(1,op.companyId().value().toString());s.setString(2,op.playerId().toString());s.setLong(3,shares);s.executeUpdate();} try(PreparedStatement s=c.prepareStatement("UPDATE companies SET total_shares=total_shares+? WHERE id=?")){s.setLong(1,shares);s.setString(2,op.companyId().value().toString());s.executeUpdate();} transition(c,id,"ESCROW_DEPOSITED","COMPLETED",now); audit(c,op.companyId(),op.playerId(),"IPO_FUNDS_AND_SHARES_ISSUED",Map.of("subscriptionId",id.toString(),"shares",shares,"amountMinor",op.amount().minorUnits()),now);closeIfExhausted(c,id,now);listIfClosedAfterCompletedSubscription(c,op.companyId(),offering,now); }
 public void closeExpired(Connection c,Instant now)throws SQLException{advanceScheduled(c,"ANNOUNCED","OPEN","opens_at<=?","OPEN_TIME",now);advanceScheduled(c,"ANNOUNCED","CLOSED","closes_at<=?","EXPIRED",now);advanceScheduled(c,"OPEN","CLOSED","closes_at<=?","EXPIRED",now);}
 public IpoSubscriptionRecoverySummary recoverSubscriptionsAtStartup(Connection c,Instant now)throws SQLException{
  int completed=0, marked=0, existing=0;
  try(PreparedStatement s=c.prepareStatement("SELECT t.id,t.state FROM treasury_operations t JOIN primary_subscriptions ps ON ps.id=t.id ORDER BY t.updated_at,t.id"); ResultSet rows=s.executeQuery()){
   while(rows.next()){ UUID id=UUID.fromString(rows.getString(1)); TreasuryOperationState state=TreasuryOperationState.valueOf(rows.getString(2));
    if(state==TreasuryOperationState.ESCROW_DEPOSITED){ completeSubscription(c,id,now); completed++; }
    else if(state==TreasuryOperationState.PREPARED||state==TreasuryOperationState.PLAYER_WITHDRAWN){ markAmbiguous(c,id,"STARTUP","启动恢复：无法证明外部资金结果，未执行 Vault 操作。",now); marked++; }
    else if(state==TreasuryOperationState.AMBIGUOUS) existing++;
   }
  }
  return new IpoSubscriptionRecoverySummary(completed,marked,existing);
 }
 public List<IpoSubscriptionRecoveryRecord> findAmbiguousSubscriptions(){
  String sql="SELECT ps.id,ps.offering_id,ps.company_id,ps.subscriber_uuid,ps.shares,ps.amount_minor,t.state,t.updated_at FROM primary_subscriptions ps JOIN treasury_operations t ON t.id=ps.id WHERE t.state='AMBIGUOUS' ORDER BY t.updated_at,ps.id";
  try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<IpoSubscriptionRecoveryRecord> result=new ArrayList<>();while(r.next())result.add(new IpoSubscriptionRecoveryRecord(UUID.fromString(r.getString(1)),UUID.fromString(r.getString(2)),new CompanyId(UUID.fromString(r.getString(3))),UUID.fromString(r.getString(4)),r.getLong(5),Money.ofMinor(r.getLong(6)),TreasuryOperationState.valueOf(r.getString(7)),Instant.parse(r.getString(8)),"启动恢复：无法证明外部资金结果，未执行 Vault 操作。"));return List.copyOf(result);}catch(SQLException e){throw new IllegalStateException("could not list ambiguous IPO subscriptions",e);}
 }
 public long companyTotalShares(CompanyId id){return number("SELECT total_shares FROM companies WHERE id=?",id.value().toString());}
 private void closeIfExhausted(Connection c,UUID subscription,Instant now)throws SQLException{try(PreparedStatement select=c.prepareStatement("SELECT id,company_id,state FROM primary_offerings WHERE id=(SELECT offering_id FROM primary_subscriptions WHERE id=?)");PreparedStatement update=c.prepareStatement("UPDATE primary_offerings SET state='CLOSED' WHERE id=? AND state=? AND maximum_shares <= (SELECT COALESCE(SUM(ps.shares),0) FROM primary_subscriptions ps JOIN treasury_operations t ON t.id=ps.id WHERE ps.offering_id=? AND t.state='COMPLETED')")){select.setString(1,subscription.toString());try(ResultSet rows=select.executeQuery()){if(!rows.next())throw new IllegalStateException("offering missing");String id=rows.getString(1),company=rows.getString(2),from=rows.getString(3);if("CLOSED".equals(from))return;update.setString(1,id);update.setString(2,from);update.setString(3,id);if(update.executeUpdate()==1){CompanyId companyId=new CompanyId(UUID.fromString(company));stateAudit(c,companyId,UUID.fromString(id),from,"CLOSED","EXHAUSTED",now);listAfterSuccessfulClose(c,companyId,UUID.fromString(id),now);}}}}
 private void advanceScheduled(Connection c,String from,String to,String condition,String reason,Instant now)throws SQLException{String query="SELECT id,company_id FROM primary_offerings WHERE state=? AND "+condition;try(PreparedStatement select=c.prepareStatement(query);PreparedStatement update=c.prepareStatement("UPDATE primary_offerings SET state=? WHERE id=? AND state=?")){select.setString(1,from);select.setString(2,now.toString());try(ResultSet rows=select.executeQuery()){while(rows.next()){UUID offering=UUID.fromString(rows.getString(1));CompanyId company=new CompanyId(UUID.fromString(rows.getString(2)));update.setString(1,to);update.setString(2,offering.toString());update.setString(3,from);if(update.executeUpdate()==1){stateAudit(c,company,offering,from,to,reason,now);if("CLOSED".equals(to))listAfterSuccessfulClose(c,company,offering,now);}}}}}
 private void listAfterSuccessfulClose(Connection c,CompanyId company,UUID offering,Instant now)throws SQLException{if(number(c,"SELECT COUNT(*) FROM primary_subscriptions ps JOIN treasury_operations t ON t.id=ps.id WHERE ps.offering_id=? AND t.state='COMPLETED'",offering.toString())==0)return;try(PreparedStatement update=c.prepareStatement("UPDATE companies SET status='LISTED' WHERE id=? AND status<>'LISTED'")){update.setString(1,company.value().toString());if(update.executeUpdate()==1)audit(c,company,null,"IPO_LISTED",Map.of("offeringId",offering.toString(),"reason","OFFERING_CLOSED_WITH_COMPLETED_SUBSCRIPTIONS"),now);}}
 private void listIfClosedAfterCompletedSubscription(Connection c,CompanyId company,UUID offering,Instant now)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT state FROM primary_offerings WHERE id=?")){s.setString(1,offering.toString());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("offering missing");if("CLOSED".equals(r.getString(1)))listAfterSuccessfulClose(c,company,offering,now);}}}
 private UUID offeringId(Connection c,UUID subscription)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT offering_id FROM primary_subscriptions WHERE id=?")){s.setString(1,subscription.toString());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("subscription missing");return UUID.fromString(r.getString(1));}}}
 private boolean isOpen(Connection c,UUID id,Instant now)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT state,opens_at,closes_at FROM primary_offerings WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("offering not found"); return !now.isBefore(Instant.parse(r.getString(2)))&&now.isBefore(Instant.parse(r.getString(3)))&&(r.getString(1).equals("ANNOUNCED")||r.getString(1).equals("OPEN"));}}}
 private void ensureOpen(Connection c,UUID id,Instant now)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT state,company_id,opens_at,closes_at FROM primary_offerings WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){if(!r.next())throw rejected(SubscriptionPreparationRejection.INVALID,"offering not found");String state=r.getString(1);if(now.isBefore(Instant.parse(r.getString(3)))||!now.isBefore(Instant.parse(r.getString(4))))throw rejected(SubscriptionPreparationRejection.NOT_OPEN,"offering is not open");if("OPEN".equals(state))return;if(!"ANNOUNCED".equals(state))throw rejected(SubscriptionPreparationRejection.NOT_OPEN,"offering is not open");try(PreparedStatement update=c.prepareStatement("UPDATE primary_offerings SET state='OPEN' WHERE id=? AND state='ANNOUNCED'")){update.setString(1,id.toString());if(update.executeUpdate()!=1)throw rejected(SubscriptionPreparationRejection.NOT_OPEN,"offering state conflict");}stateAudit(c,new CompanyId(UUID.fromString(r.getString(2))),id,"ANNOUNCED","OPEN","OPEN_TIME",now);}}}
 private static SubscriptionPreparationRejectedException rejected(SubscriptionPreparationRejection rejection,String message){return new SubscriptionPreparationRejectedException(rejection,message);} private static SubscriptionPreparationRejectedException rejected(SubscriptionPreparationRejection rejection,String message,Throwable cause){return new SubscriptionPreparationRejectedException(rejection,message,cause);}
 private void transition(Connection c,UUID id,String from,String to,Instant now)throws SQLException{TreasuryOperation op=operation(c,id);try(PreparedStatement s=c.prepareStatement("UPDATE treasury_operations SET state=?,updated_at=? WHERE id=? AND state=?")){s.setString(1,to);s.setString(2,now.toString());s.setString(3,id.toString());s.setString(4,from);if(s.executeUpdate()!=1)throw new IllegalStateException("subscription state conflict");}audit(c,op.companyId(),op.playerId(),"IPO_TREASURY_"+to,Map.of("subscriptionId",id.toString(),"from",from,"to",to),now);}
 private TreasuryOperation operation(Connection c,UUID id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM treasury_operations WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("subscription not found");return new TreasuryOperation(id,new CompanyId(UUID.fromString(r.getString("company_id"))),UUID.fromString(r.getString("player_uuid")),Money.ofMinor(r.getLong("amount_minor")),r.getString("provider_correlation_key"),TreasuryOperationState.valueOf(r.getString("state")),Instant.parse(r.getString("created_at")),Instant.parse(r.getString("updated_at")));}}}
 private Optional<TreasuryOperation> findOperation(Connection c,UUID id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM treasury_operations WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){if(!r.next())return Optional.empty();return Optional.of(new TreasuryOperation(id,new CompanyId(UUID.fromString(r.getString("company_id"))),UUID.fromString(r.getString("player_uuid")),Money.ofMinor(r.getLong("amount_minor")),r.getString("provider_correlation_key"),TreasuryOperationState.valueOf(r.getString("state")),Instant.parse(r.getString("created_at")),Instant.parse(r.getString("updated_at"))));}}}
 private long number(String sql,String... values){try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(sql)){for(int i=0;i<values.length;i++)s.setString(i+1,values[i]);try(ResultSet r=s.executeQuery()){r.next();return r.getLong(1);}}catch(SQLException e){throw new IllegalStateException("could not read offering",e);}} private long number(Connection c,String sql,String v)throws SQLException{try(PreparedStatement s=c.prepareStatement(sql)){s.setString(1,v);try(ResultSet r=s.executeQuery()){r.next();return r.getLong(1);}}}
 private PrimaryOffering offer(ResultSet r)throws SQLException{return new PrimaryOffering(UUID.fromString(r.getString("id")),new CompanyId(UUID.fromString(r.getString("company_id"))),Money.ofMinor(r.getLong("target_minor")),Money.ofMinor(r.getLong("issue_price_minor")),r.getLong("maximum_shares"),Instant.parse(r.getString("announced_at")),Instant.parse(r.getString("opens_at")),Instant.parse(r.getString("closes_at")),PrimaryOfferingState.valueOf(r.getString("state")));} private void announcement(Connection c,PrimaryOffering o,String body)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO company_announcements VALUES (?,?,?,?,?)")){s.setString(1,UUID.randomUUID().toString());s.setString(2,o.companyId().value().toString());s.setString(3,o.id().toString());s.setString(4,body);s.setString(5,o.announcedAt().toString());s.executeUpdate();}} private void stateAudit(Connection c,CompanyId company,UUID offering,String from,String to,String reason,Instant at)throws SQLException{audit(c,company,null,"IPO_STATE_CHANGED",Map.of("offeringId",offering.toString(),"companyId",company.value().toString(),"from",from,"to",to,"reason",reason,"actor","","source","SCHEDULER"),at);} private void audit(Connection c,CompanyId company,UUID actor,String type,Map<String,Object> payload,Instant at)throws SQLException{audits.append(c,new AuditEvent(UUID.randomUUID(),Optional.of(company),Optional.ofNullable(actor),type,payload,at));}
 private static String publicOfferingSql(){return "SELECT po.id offering_id, po.company_id offering_company_id, c.display_name, po.state, po.target_minor, po.issue_price_minor, po.maximum_shares, po.announced_at, po.opens_at, po.closes_at, COALESCE(SUM(CASE WHEN t.state='COMPLETED' THEN ps.shares ELSE 0 END),0) issued_shares, COALESCE(SUM(CASE WHEN t.state<>'REFUNDED' THEN ps.shares ELSE 0 END),0) reserved_shares FROM primary_offerings po JOIN companies c ON c.id=po.company_id LEFT JOIN primary_subscriptions ps ON ps.offering_id=po.id LEFT JOIN treasury_operations t ON t.id=ps.id WHERE po.state IN ('ANNOUNCED','OPEN','CLOSED')";}
 private static PublicOfferingView publicOffer(ResultSet r)throws SQLException{long maximum=r.getLong("maximum_shares"),reserved=r.getLong("reserved_shares");return new PublicOfferingView(UUID.fromString(r.getString("offering_id")),new CompanyId(UUID.fromString(r.getString("offering_company_id"))),r.getString("display_name"),PrimaryOfferingState.valueOf(r.getString("state")),Money.ofMinor(r.getLong("target_minor")),Money.ofMinor(r.getLong("issue_price_minor")),maximum,r.getLong("issued_shares"),reserved,Math.subtractExact(maximum,reserved),Instant.parse(r.getString("announced_at")),Instant.parse(r.getString("opens_at")),Instant.parse(r.getString("closes_at")));}
}
