package cn.blockeco.exchange.infrastructure.sql;

import cn.blockeco.exchange.domain.company.CompanyId;
import cn.blockeco.exchange.domain.audit.AuditEvent;
import cn.blockeco.exchange.domain.finance.*;
import cn.blockeco.exchange.domain.money.Money;
import cn.blockeco.exchange.ports.PrimaryOfferingRepository;
import java.sql.*; import java.time.Instant; import java.util.*; import javax.sql.DataSource;

public final class SqlPrimaryOfferingRepository implements PrimaryOfferingRepository {
 private final DataSource ds; private final SqlAuditLog audits=new SqlAuditLog(); public SqlPrimaryOfferingRepository(DataSource ds){this.ds=ds;}
 public void announce(Connection c,PrimaryOffering o)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO primary_offerings VALUES (?,?,?,?,?,?,?,?,?)")){s.setString(1,o.id().toString());s.setString(2,o.companyId().value().toString());s.setLong(3,o.target().minorUnits());s.setLong(4,o.issuePrice().minorUnits());s.setLong(5,o.maximumShares());s.setString(6,o.announcedAt().toString());s.setString(7,o.opensAt().toString());s.setString(8,o.closesAt().toString());s.setString(9,o.state().name());s.executeUpdate();} announcement(c,o,"首次公开发行公告：认购编号="+o.id()+"；目标="+o.target().minorUnits()+"；发行价="+o.issuePrice().minorUnits()+"；最大股数="+o.maximumShares()+"；开放="+o.opensAt()+"；结束="+o.closesAt()+"；实缴资本="+number(c,"SELECT paid_in_capital_minor FROM company_cash_accounts WHERE company_id=?",o.companyId().value().toString())+"；风险提示：股票价格可能波动，投资有风险，不承诺收益。");audit(c,o.companyId(),null,"IPO_ANNOUNCED",Map.of("offeringId",o.id().toString(),"targetMinor",o.target().minorUnits(),"issuePriceMinor",o.issuePrice().minorUnits()),o.announcedAt());}
 public Optional<PrimaryOffering> find(UUID id){try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement("SELECT * FROM primary_offerings WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(offer(r)):Optional.empty();}}catch(SQLException e){throw new IllegalStateException("could not find offering",e);}}
 public long paidInCapital(CompanyId id){return number("SELECT paid_in_capital_minor FROM company_cash_accounts WHERE company_id=?",id.value().toString());}
 public boolean hasActiveAsset(CompanyId id){return number("SELECT COUNT(*) FROM asset_bindings WHERE company_id=? AND state='ACTIVE'",id.value().toString())>0;}
 public boolean isFounder(CompanyId id,UUID founder){return number("SELECT COUNT(*) FROM companies WHERE id=? AND founder_uuid=?",id.value().toString(),founder.toString())==1;}
 public SubscriptionPreparation prepareSubscription(Connection c,UUID id,PrimaryOffering o,UUID subscriber,long shares,Instant now)throws SQLException{ Optional<TreasuryOperation> existing=findOperation(c,id); if(existing.isPresent()) return new SubscriptionPreparation(existing.get(),false); if(shares<=0)throw new IllegalArgumentException("shares must be positive"); ensureOpen(c,o.id(),now); long issued=number(c,"SELECT COALESCE(SUM(shares),0) FROM primary_subscriptions WHERE offering_id=?",o.id().toString()); if(shares>o.maximumShares()-issued)throw new IllegalStateException("insufficient offering shares"); long amount=Math.multiplyExact(shares,o.issuePrice().minorUnits()); try(PreparedStatement s=c.prepareStatement("INSERT INTO primary_subscriptions VALUES (?,?,?,?,?,?,?,?)")){s.setString(1,id.toString());s.setString(2,o.id().toString());s.setString(3,o.companyId().value().toString());s.setString(4,subscriber.toString());s.setLong(5,shares);s.setLong(6,amount);s.setString(7,id.toString());s.setString(8,now.toString());s.executeUpdate();} try(PreparedStatement s=c.prepareStatement("INSERT INTO treasury_operations VALUES (?,?,?,?,?,?,?,?)")){s.setString(1,id.toString());s.setString(2,o.companyId().value().toString());s.setString(3,subscriber.toString());s.setLong(4,amount);s.setString(5,id.toString());s.setString(6,"PREPARED");s.setString(7,now.toString());s.setString(8,now.toString());s.executeUpdate();} return new SubscriptionPreparation(new TreasuryOperation(id,o.companyId(),subscriber,Money.ofMinor(amount),id.toString(),TreasuryOperationState.PREPARED,now,now),true); }
 public void markWithdrawn(Connection c,UUID id,Instant now)throws SQLException{transition(c,id,"PREPARED","PLAYER_WITHDRAWN",now);} public void markEscrowDeposited(Connection c,UUID id,Instant now)throws SQLException{transition(c,id,"PLAYER_WITHDRAWN","ESCROW_DEPOSITED",now);} public void markAmbiguous(Connection c,UUID id,String expected,Instant now)throws SQLException{if(operation(c,id).state()==TreasuryOperationState.AMBIGUOUS)return;transition(c,id,expected,"AMBIGUOUS",now);}
 public void completeSubscription(Connection c,UUID id,Instant now)throws SQLException{ TreasuryOperation op=operation(c,id); if(op.state()==TreasuryOperationState.COMPLETED)return; if(op.state()!=TreasuryOperationState.ESCROW_DEPOSITED)throw new IllegalStateException("subscription requires recovery"); UUID offering=offeringId(c,id); long shares=number(c,"SELECT shares FROM primary_subscriptions WHERE id=?",id.toString()); try(PreparedStatement s=c.prepareStatement("UPDATE company_cash_accounts SET cash_minor=cash_minor+? WHERE company_id=?")){s.setLong(1,op.amount().minorUnits());s.setString(2,op.companyId().value().toString());if(s.executeUpdate()!=1)throw new IllegalStateException("cash account missing");} try(PreparedStatement s=c.prepareStatement("INSERT INTO share_holdings (company_id,holder_uuid,available_shares,reserved_shares) VALUES (?,?,?,0) ON CONFLICT(company_id,holder_uuid) DO UPDATE SET available_shares=available_shares+excluded.available_shares")){s.setString(1,op.companyId().value().toString());s.setString(2,op.playerId().toString());s.setLong(3,shares);s.executeUpdate();} try(PreparedStatement s=c.prepareStatement("UPDATE companies SET total_shares=total_shares+? WHERE id=?")){s.setLong(1,shares);s.setString(2,op.companyId().value().toString());s.executeUpdate();} transition(c,id,"ESCROW_DEPOSITED","COMPLETED",now); audit(c,op.companyId(),op.playerId(),"IPO_FUNDS_AND_SHARES_ISSUED",Map.of("subscriptionId",id.toString(),"shares",shares,"amountMinor",op.amount().minorUnits()),now);closeIfExhausted(c,id,now);listIfClosedAfterCompletedSubscription(c,op.companyId(),offering,now); }
 public void closeExpired(Connection c,Instant now)throws SQLException{advanceScheduled(c,"ANNOUNCED","OPEN","opens_at<=?","OPEN_TIME",now);advanceScheduled(c,"ANNOUNCED","CLOSED","closes_at<=?","EXPIRED",now);advanceScheduled(c,"OPEN","CLOSED","closes_at<=?","EXPIRED",now);}
 public long companyTotalShares(CompanyId id){return number("SELECT total_shares FROM companies WHERE id=?",id.value().toString());}
 private void closeIfExhausted(Connection c,UUID subscription,Instant now)throws SQLException{try(PreparedStatement select=c.prepareStatement("SELECT id,company_id,state FROM primary_offerings WHERE id=(SELECT offering_id FROM primary_subscriptions WHERE id=?)");PreparedStatement update=c.prepareStatement("UPDATE primary_offerings SET state='CLOSED' WHERE id=? AND state=? AND maximum_shares <= (SELECT COALESCE(SUM(shares),0) FROM primary_subscriptions WHERE offering_id=?)")){select.setString(1,subscription.toString());try(ResultSet rows=select.executeQuery()){if(!rows.next())throw new IllegalStateException("offering missing");String id=rows.getString(1),company=rows.getString(2),from=rows.getString(3);if("CLOSED".equals(from))return;update.setString(1,id);update.setString(2,from);update.setString(3,id);if(update.executeUpdate()==1){CompanyId companyId=new CompanyId(UUID.fromString(company));stateAudit(c,companyId,UUID.fromString(id),from,"CLOSED","EXHAUSTED",now);listAfterSuccessfulClose(c,companyId,UUID.fromString(id),now);}}}}
 private void advanceScheduled(Connection c,String from,String to,String condition,String reason,Instant now)throws SQLException{String query="SELECT id,company_id FROM primary_offerings WHERE state=? AND "+condition;try(PreparedStatement select=c.prepareStatement(query);PreparedStatement update=c.prepareStatement("UPDATE primary_offerings SET state=? WHERE id=? AND state=?")){select.setString(1,from);select.setString(2,now.toString());try(ResultSet rows=select.executeQuery()){while(rows.next()){UUID offering=UUID.fromString(rows.getString(1));CompanyId company=new CompanyId(UUID.fromString(rows.getString(2)));update.setString(1,to);update.setString(2,offering.toString());update.setString(3,from);if(update.executeUpdate()==1){stateAudit(c,company,offering,from,to,reason,now);if("CLOSED".equals(to))listAfterSuccessfulClose(c,company,offering,now);}}}}}
 private void listAfterSuccessfulClose(Connection c,CompanyId company,UUID offering,Instant now)throws SQLException{if(number(c,"SELECT COUNT(*) FROM primary_subscriptions ps JOIN treasury_operations t ON t.id=ps.id WHERE ps.offering_id=? AND t.state='COMPLETED'",offering.toString())==0)return;try(PreparedStatement update=c.prepareStatement("UPDATE companies SET status='LISTED' WHERE id=? AND status<>'LISTED'")){update.setString(1,company.value().toString());if(update.executeUpdate()==1)audit(c,company,null,"IPO_LISTED",Map.of("offeringId",offering.toString(),"reason","OFFERING_CLOSED_WITH_COMPLETED_SUBSCRIPTIONS"),now);}}
 private void listIfClosedAfterCompletedSubscription(Connection c,CompanyId company,UUID offering,Instant now)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT state FROM primary_offerings WHERE id=?")){s.setString(1,offering.toString());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("offering missing");if("CLOSED".equals(r.getString(1)))listAfterSuccessfulClose(c,company,offering,now);}}}
 private UUID offeringId(Connection c,UUID subscription)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT offering_id FROM primary_subscriptions WHERE id=?")){s.setString(1,subscription.toString());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("subscription missing");return UUID.fromString(r.getString(1));}}}
 private boolean isOpen(Connection c,UUID id,Instant now)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT state,opens_at,closes_at FROM primary_offerings WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("offering not found"); return !now.isBefore(Instant.parse(r.getString(2)))&&now.isBefore(Instant.parse(r.getString(3)))&&(r.getString(1).equals("ANNOUNCED")||r.getString(1).equals("OPEN"));}}}
 private void ensureOpen(Connection c,UUID id,Instant now)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT state,company_id,opens_at,closes_at FROM primary_offerings WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("offering not found");String state=r.getString(1);if(now.isBefore(Instant.parse(r.getString(3)))||!now.isBefore(Instant.parse(r.getString(4))))throw new IllegalStateException("offering is not open");if("OPEN".equals(state))return;if(!"ANNOUNCED".equals(state))throw new IllegalStateException("offering is not open");try(PreparedStatement update=c.prepareStatement("UPDATE primary_offerings SET state='OPEN' WHERE id=? AND state='ANNOUNCED'")){update.setString(1,id.toString());if(update.executeUpdate()!=1)throw new IllegalStateException("offering state conflict");}stateAudit(c,new CompanyId(UUID.fromString(r.getString(2))),id,"ANNOUNCED","OPEN","OPEN_TIME",now);}}}
 private void transition(Connection c,UUID id,String from,String to,Instant now)throws SQLException{TreasuryOperation op=operation(c,id);try(PreparedStatement s=c.prepareStatement("UPDATE treasury_operations SET state=?,updated_at=? WHERE id=? AND state=?")){s.setString(1,to);s.setString(2,now.toString());s.setString(3,id.toString());s.setString(4,from);if(s.executeUpdate()!=1)throw new IllegalStateException("subscription state conflict");}audit(c,op.companyId(),op.playerId(),"IPO_TREASURY_"+to,Map.of("subscriptionId",id.toString(),"from",from,"to",to),now);}
 private TreasuryOperation operation(Connection c,UUID id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM treasury_operations WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("subscription not found");return new TreasuryOperation(id,new CompanyId(UUID.fromString(r.getString("company_id"))),UUID.fromString(r.getString("player_uuid")),Money.ofMinor(r.getLong("amount_minor")),r.getString("provider_correlation_key"),TreasuryOperationState.valueOf(r.getString("state")),Instant.parse(r.getString("created_at")),Instant.parse(r.getString("updated_at")));}}}
 private Optional<TreasuryOperation> findOperation(Connection c,UUID id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM treasury_operations WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){if(!r.next())return Optional.empty();return Optional.of(new TreasuryOperation(id,new CompanyId(UUID.fromString(r.getString("company_id"))),UUID.fromString(r.getString("player_uuid")),Money.ofMinor(r.getLong("amount_minor")),r.getString("provider_correlation_key"),TreasuryOperationState.valueOf(r.getString("state")),Instant.parse(r.getString("created_at")),Instant.parse(r.getString("updated_at"))));}}}
 private long number(String sql,String... values){try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(sql)){for(int i=0;i<values.length;i++)s.setString(i+1,values[i]);try(ResultSet r=s.executeQuery()){r.next();return r.getLong(1);}}catch(SQLException e){throw new IllegalStateException("could not read offering",e);}} private long number(Connection c,String sql,String v)throws SQLException{try(PreparedStatement s=c.prepareStatement(sql)){s.setString(1,v);try(ResultSet r=s.executeQuery()){r.next();return r.getLong(1);}}}
 private PrimaryOffering offer(ResultSet r)throws SQLException{return new PrimaryOffering(UUID.fromString(r.getString("id")),new CompanyId(UUID.fromString(r.getString("company_id"))),Money.ofMinor(r.getLong("target_minor")),Money.ofMinor(r.getLong("issue_price_minor")),r.getLong("maximum_shares"),Instant.parse(r.getString("announced_at")),Instant.parse(r.getString("opens_at")),Instant.parse(r.getString("closes_at")),PrimaryOfferingState.valueOf(r.getString("state")));} private void announcement(Connection c,PrimaryOffering o,String body)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO company_announcements VALUES (?,?,?,?,?)")){s.setString(1,UUID.randomUUID().toString());s.setString(2,o.companyId().value().toString());s.setString(3,o.id().toString());s.setString(4,body);s.setString(5,o.announcedAt().toString());s.executeUpdate();}} private void stateAudit(Connection c,CompanyId company,UUID offering,String from,String to,String reason,Instant at)throws SQLException{audit(c,company,null,"IPO_STATE_CHANGED",Map.of("offeringId",offering.toString(),"companyId",company.value().toString(),"from",from,"to",to,"reason",reason,"actor","","source","SCHEDULER"),at);} private void audit(Connection c,CompanyId company,UUID actor,String type,Map<String,Object> payload,Instant at)throws SQLException{audits.append(c,new AuditEvent(UUID.randomUUID(),Optional.of(company),Optional.ofNullable(actor),type,payload,at));}
}
