package cn.blockeco.exchange.infrastructure.sql;

import cn.blockeco.exchange.domain.company.CompanyId;
import cn.blockeco.exchange.domain.finance.ShareHolding;
import cn.blockeco.exchange.domain.money.Money;
import cn.blockeco.exchange.domain.trading.FeePolicy;
import cn.blockeco.exchange.domain.trading.LimitOrder;
import cn.blockeco.exchange.domain.trading.Trade;
import cn.blockeco.exchange.ports.SecondaryTradingRepository;
import java.sql.*;
import java.time.Instant;
import java.util.*;
import javax.sql.DataSource;

/** SQLite implementation.  This class intentionally owns no transaction boundary. */
public final class SqlSecondaryTradingRepository implements SecondaryTradingRepository {
    private final DataSource dataSource; private final SqlSecuritiesCashRepository cash;
    public SqlSecondaryTradingRepository(DataSource dataSource, SqlSecuritiesCashRepository cash) { this.dataSource=Objects.requireNonNull(dataSource);this.cash=Objects.requireNonNull(cash); }
    @Override public void reserveBuy(Connection c, LimitOrder order)throws SQLException { requireBuy(order); cash.reserve(c,order.playerId(),order.reservedCash()); insertOrder(c,order); }
    @Override public void reserveSell(Connection c, LimitOrder order)throws SQLException { if(order.side()!=LimitOrder.Side.SELL)throw new IllegalArgumentException("sell order required"); reserveShares(c,order.companyId(),order.playerId(),order.remainingShares()); insertOrder(c,order); }
    @Override public Settlement settleTrade(Connection c, Trade trade)throws SQLException {
        LimitOrder buy=load(c,trade.buyOrderId()),sell=load(c,trade.sellOrderId()); validateFill(buy,sell,trade);
        long newFilledNotional=Math.addExact(buy.filledNotional().minorUnits(),trade.notional().minorUnits());
        long newFee=FeePolicy.cumulativeFee(Money.ofMinor(newFilledNotional),buy.feeBps()).minorUnits();
        long feeDelta=Math.subtractExact(newFee,buy.feeCharged().minorUnits());
        if(feeDelta!=trade.buyerFee().minorUnits())throw new OptimisticStateException("trade fee does not match cumulative order fee");
        long remainingBuy=Math.subtractExact(buy.remainingShares(),trade.shares()), remainingSell=Math.subtractExact(sell.remainingShares(),trade.shares());
        long newReserve=requiredReserve(remainingBuy,buy.limitPrice().minorUnits(),newFilledNotional,newFee,buy.feeBps());
        long buyerDebit=Math.addExact(trade.notional().minorUnits(),feeDelta);
        long released=Math.subtractExact(buy.reservedCash().minorUnits(),Math.addExact(buyerDebit,newReserve));
        if(released<0)throw new OptimisticStateException("buy reserve is insufficient for fill");
        insertTrade(c,trade);
        cash.adjustReservedToAvailable(c,buy.playerId(),Math.addExact(buyerDebit,released),released);
        updateSharesAfterBuy(c,buy.companyId(),buy.playerId(),trade.shares());
        updateSharesAfterSell(c,sell.companyId(),sell.playerId(),trade.shares());
        cash.creditFromTrade(c,sell.playerId(),trade.notional().minorUnits());
        cash.ledger(c,"SECURITIES_CASH",null,sell.playerId(),trade.notional().minorUnits(),null,trade.id(),trade.occurredAt());
        cash.ledger(c,"SECURITIES_CASH",null,buy.playerId(),-feeDelta,null,trade.id(),trade.occurredAt());
        cash.creditCompensation(c,feeDelta,trade.id(),trade.occurredAt());
        updateOrder(c,buy,remainingBuy,newReserve,newFilledNotional,newFee);
        updateOrder(c,sell,remainingSell,0,0,0);
        return new Settlement(load(c,buy.id()),load(c,sell.id()),Money.ofMinor(released));
    }
    @Override public void releaseOrder(Connection c, UUID orderId, LimitOrder.State terminal)throws SQLException { if(terminal!=LimitOrder.State.CANCELLED&&terminal!=LimitOrder.State.SELF_TRADE_PREVENTED)throw new IllegalArgumentException("terminal cancellation state required"); LimitOrder o=load(c,orderId); if(o.state()==terminal)return; if(o.state()!=LimitOrder.State.OPEN&&o.state()!=LimitOrder.State.PARTIALLY_FILLED)throw new OptimisticStateException("order is no longer active"); if(o.side()==LimitOrder.Side.BUY)cash.release(c,o.playerId(),o.reservedCash());else releaseShares(c,o.companyId(),o.playerId(),o.remainingShares()); updateTerminal(c,o,terminal); }
    @Override public void cancelTakerForSelfTrade(Connection c, UUID orderId)throws SQLException { releaseOrder(c,orderId,LimitOrder.State.SELF_TRADE_PREVENTED); }
    @Override public Optional<LimitOrder> findOrder(UUID id){try(Connection c=dataSource.getConnection()){return find(c,id);}catch(SQLException e){throw new IllegalStateException("could not find stock order",e);}}
    @Override public Optional<ShareHolding> findHolding(CompanyId company,UUID p){try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement("SELECT available_shares,reserved_shares FROM share_holdings WHERE company_id=? AND holder_uuid=?")){s.setString(1,company.value().toString());s.setString(2,p.toString());try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(new ShareHolding(company,p,r.getLong(1),r.getLong(2))):Optional.empty();}}catch(SQLException e){throw new IllegalStateException("could not find share holding",e);}}
    @Override public Money compensationFund(){try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement("SELECT balance_minor FROM compensation_fund WHERE singleton=1");ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("compensation fund missing");return Money.ofMinor(r.getLong(1));}catch(SQLException e){throw new IllegalStateException("could not read compensation fund",e);}}
    private void insertOrder(Connection c,LimitOrder o)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO stock_orders (id,company_id,stock_code,player_uuid,side,limit_price_minor,original_shares,remaining_shares,priority_sequence,reserved_cash_minor,filled_notional_minor,fee_charged_minor,fee_bps,accepted_at,state) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){s.setString(1,o.id().toString());s.setString(2,o.companyId().value().toString());s.setString(3,o.stockCode());s.setString(4,o.playerId().toString());s.setString(5,o.side().name());s.setLong(6,o.limitPrice().minorUnits());s.setLong(7,o.originalShares());s.setLong(8,o.remainingShares());s.setLong(9,o.prioritySequence());s.setLong(10,o.reservedCash().minorUnits());s.setLong(11,o.filledNotional().minorUnits());s.setLong(12,o.feeCharged().minorUnits());s.setInt(13,o.feeBps());s.setString(14,o.acceptedAt().toString());s.setString(15,o.state().name());s.executeUpdate();}}
    private void insertTrade(Connection c,Trade t)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO stock_trades (id,company_id,stock_code,buy_order_id,sell_order_id,shares,price_minor,notional_minor,buyer_fee_minor,occurred_at) VALUES (?,?,?,?,?,?,?,?,?,?)")){s.setString(1,t.id().toString());s.setString(2,t.companyId().value().toString());s.setString(3,t.stockCode());s.setString(4,t.buyOrderId().toString());s.setString(5,t.sellOrderId().toString());s.setLong(6,t.shares());s.setLong(7,t.price().minorUnits());s.setLong(8,t.notional().minorUnits());s.setLong(9,t.buyerFee().minorUnits());s.setString(10,t.occurredAt().toString());s.executeUpdate();}}
    private void reserveShares(Connection c,CompanyId company,UUID p,long shares)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE share_holdings SET available_shares=available_shares-?,reserved_shares=reserved_shares+? WHERE company_id=? AND holder_uuid=? AND available_shares>=?")){s.setLong(1,shares);s.setLong(2,shares);s.setString(3,company.value().toString());s.setString(4,p.toString());s.setLong(5,shares);if(s.executeUpdate()!=1)throw new InsufficientSharesException("insufficient available shares");}}
    private void releaseShares(Connection c,CompanyId company,UUID p,long shares)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE share_holdings SET available_shares=available_shares+?,reserved_shares=reserved_shares-? WHERE company_id=? AND holder_uuid=? AND reserved_shares>=?")){s.setLong(1,shares);s.setLong(2,shares);s.setString(3,company.value().toString());s.setString(4,p.toString());s.setLong(5,shares);if(s.executeUpdate()!=1)throw new OptimisticStateException("share reserve state conflict");}}
    private void updateSharesAfterBuy(Connection c,CompanyId co,UUID p,long shares)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO share_holdings (company_id,holder_uuid,available_shares,reserved_shares) VALUES (?,?,?,0) ON CONFLICT(company_id,holder_uuid) DO UPDATE SET available_shares=share_holdings.available_shares+excluded.available_shares")){s.setString(1,co.value().toString());s.setString(2,p.toString());s.setLong(3,shares);s.executeUpdate();}}
    private void updateSharesAfterSell(Connection c,CompanyId co,UUID p,long shares)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE share_holdings SET reserved_shares=reserved_shares-? WHERE company_id=? AND holder_uuid=? AND reserved_shares>=?")){s.setLong(1,shares);s.setString(2,co.value().toString());s.setString(3,p.toString());s.setLong(4,shares);if(s.executeUpdate()!=1)throw new OptimisticStateException("seller reserve state conflict");}}
    private void updateOrder(Connection c,LimitOrder o,long remaining,long reserve,long filled,long fee)throws SQLException{LimitOrder.State state=remaining==0?LimitOrder.State.FILLED:LimitOrder.State.PARTIALLY_FILLED;try(PreparedStatement s=c.prepareStatement("UPDATE stock_orders SET remaining_shares=?,reserved_cash_minor=?,filled_notional_minor=?,fee_charged_minor=?,state=? WHERE id=? AND remaining_shares=? AND reserved_cash_minor=? AND filled_notional_minor=? AND fee_charged_minor=? AND state=?")){s.setLong(1,remaining);s.setLong(2,reserve);s.setLong(3,filled);s.setLong(4,fee);s.setString(5,state.name());s.setString(6,o.id().toString());s.setLong(7,o.remainingShares());s.setLong(8,o.reservedCash().minorUnits());s.setLong(9,o.filledNotional().minorUnits());s.setLong(10,o.feeCharged().minorUnits());s.setString(11,o.state().name());if(s.executeUpdate()!=1)throw new OptimisticStateException("order state conflict");}}
    private void updateTerminal(Connection c,LimitOrder o,LimitOrder.State terminal)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE stock_orders SET reserved_cash_minor=0,state=? WHERE id=? AND state=?")){s.setString(1,terminal.name());s.setString(2,o.id().toString());s.setString(3,o.state().name());if(s.executeUpdate()!=1)throw new OptimisticStateException("order cancellation state conflict");}}
    private LimitOrder load(Connection c,UUID id)throws SQLException{return find(c,id).orElseThrow(()->new OptimisticStateException("stock order missing: "+id));}
    private Optional<LimitOrder> find(Connection c,UUID id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM stock_orders WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(read(r)):Optional.empty();}}}
    private static LimitOrder read(ResultSet r)throws SQLException{return new LimitOrder(UUID.fromString(r.getString("id")),new CompanyId(UUID.fromString(r.getString("company_id"))),r.getString("stock_code"),UUID.fromString(r.getString("player_uuid")),LimitOrder.Side.valueOf(r.getString("side")),Money.ofMinor(r.getLong("limit_price_minor")),r.getLong("original_shares"),r.getLong("remaining_shares"),r.getLong("priority_sequence"),Money.ofMinor(r.getLong("reserved_cash_minor")),Money.ofMinor(r.getLong("filled_notional_minor")),Money.ofMinor(r.getLong("fee_charged_minor")),r.getInt("fee_bps"),Instant.parse(r.getString("accepted_at")),LimitOrder.State.valueOf(r.getString("state")));}
    private static void requireBuy(LimitOrder o){if(o.side()!=LimitOrder.Side.BUY)throw new IllegalArgumentException("buy order required");}
    private static void validateFill(LimitOrder b,LimitOrder s,Trade t){if(b.side()!=LimitOrder.Side.BUY||s.side()!=LimitOrder.Side.SELL||!b.companyId().equals(s.companyId())||!b.stockCode().equals(s.stockCode())||!b.companyId().equals(t.companyId())||!b.stockCode().equals(t.stockCode()))throw new OptimisticStateException("trade orders do not match");if(b.playerId().equals(s.playerId()))throw new OptimisticStateException("self trade must be prevented before settlement");if(b.state()!=LimitOrder.State.OPEN&&b.state()!=LimitOrder.State.PARTIALLY_FILLED)throw new OptimisticStateException("buy order not active");if(s.state()!=LimitOrder.State.OPEN&&s.state()!=LimitOrder.State.PARTIALLY_FILLED)throw new OptimisticStateException("sell order not active");if(t.shares()>b.remainingShares()||t.shares()>s.remainingShares()||t.price().minorUnits()>b.limitPrice().minorUnits()||t.price().minorUnits()<s.limitPrice().minorUnits())throw new OptimisticStateException("invalid fill");}
    private static long requiredReserve(long shares,long price,long filled,long fee,int bps){if(shares==0)return 0;long worst=Math.addExact(filled,Math.multiplyExact(shares,price));return Math.addExact(Math.multiplyExact(shares,price),Math.subtractExact(FeePolicy.cumulativeFee(Money.ofMinor(worst),bps).minorUnits(),fee));}
}
