package cn.blockeco.exchange.infrastructure.sql;

import cn.blockeco.exchange.domain.finance.EscrowReconciliation;
import cn.blockeco.exchange.domain.finance.SecuritiesCashAccount;
import cn.blockeco.exchange.domain.money.Money;
import cn.blockeco.exchange.ports.SecuritiesCashRepository;
import cn.blockeco.exchange.ports.SecondaryTradingRepository;
import java.sql.*;
import java.time.Instant;
import java.util.*;
import javax.sql.DataSource;

public final class SqlSecuritiesCashRepository implements SecuritiesCashRepository {
    private final DataSource dataSource;
    public SqlSecuritiesCashRepository(DataSource dataSource) { this.dataSource = Objects.requireNonNull(dataSource); }
    @Override public Optional<SecuritiesCashAccount> find(UUID playerId) {
        try (Connection c=dataSource.getConnection(); PreparedStatement s=c.prepareStatement("SELECT available_minor,reserved_minor FROM securities_cash_accounts WHERE player_uuid=?")) { s.setString(1,playerId.toString()); try(ResultSet r=s.executeQuery()) { return r.next()?Optional.of(new SecuritiesCashAccount(playerId,Money.ofMinor(r.getLong(1)),Money.ofMinor(r.getLong(2)))):Optional.empty(); } } catch(SQLException e){throw new IllegalStateException("could not read securities cash",e);}
    }
    @Override public void creditAvailable(Connection c, UUID player, Money amount, Instant at) throws SQLException { requirePositive(amount); upsert(c,player,amount.minorUnits(),0); ledger(c,"SECURITIES_CASH",null,player,amount.minorUnits(),null,null,at); }
    @Override public void reserve(Connection c, UUID player, Money amount) throws SQLException { requirePositive(amount); try(PreparedStatement s=c.prepareStatement("UPDATE securities_cash_accounts SET available_minor=available_minor-?, reserved_minor=reserved_minor+? WHERE player_uuid=? AND available_minor>=?")){s.setLong(1,amount.minorUnits());s.setLong(2,amount.minorUnits());s.setString(3,player.toString());s.setLong(4,amount.minorUnits());if(s.executeUpdate()!=1)throw new SecondaryTradingRepository.InsufficientCashException("insufficient available securities cash");} }
    @Override public void release(Connection c, UUID player, Money amount) throws SQLException { requirePositive(amount); try(PreparedStatement s=c.prepareStatement("UPDATE securities_cash_accounts SET available_minor=available_minor+?, reserved_minor=reserved_minor-? WHERE player_uuid=? AND reserved_minor>=?")){s.setLong(1,amount.minorUnits());s.setLong(2,amount.minorUnits());s.setString(3,player.toString());s.setLong(4,amount.minorUnits());if(s.executeUpdate()!=1)throw new SecondaryTradingRepository.OptimisticStateException("cash reserve state conflict");} }
    void adjustReservedToAvailable(Connection c, UUID player, long debitReserved, long creditAvailable) throws SQLException { if(debitReserved<0||creditAvailable<0||debitReserved<creditAvailable)throw new IllegalArgumentException("invalid cash settlement adjustment"); try(PreparedStatement s=c.prepareStatement("UPDATE securities_cash_accounts SET reserved_minor=reserved_minor-?, available_minor=available_minor+? WHERE player_uuid=? AND reserved_minor>=?")){s.setLong(1,debitReserved);s.setLong(2,creditAvailable);s.setString(3,player.toString());s.setLong(4,debitReserved);if(s.executeUpdate()!=1)throw new SecondaryTradingRepository.OptimisticStateException("buyer reserve state conflict");} }
    void creditFromTrade(Connection c, UUID player, long amount) throws SQLException { if(amount<0)throw new IllegalArgumentException("negative credit"); upsert(c,player,amount,0); }
    void creditCompensation(Connection c,long amount,UUID trade,Instant at)throws SQLException { if(amount==0)return; if(amount<0)throw new IllegalArgumentException("negative compensation credit");try(PreparedStatement s=c.prepareStatement("UPDATE compensation_fund SET balance_minor=balance_minor+? WHERE singleton=1 AND balance_minor<=?")){s.setLong(1,amount);s.setLong(2,Math.subtractExact(Long.MAX_VALUE,amount));if(s.executeUpdate()!=1)throw new ArithmeticException("compensation fund overflow or missing");}ledger(c,"COMPENSATION_FUND",null,null,amount,null,trade,at); }
    void ledger(Connection c,String kind,UUID company,UUID player,long amount,UUID operation,UUID trade,Instant at)throws SQLException { if(amount==0)return;try(PreparedStatement s=c.prepareStatement("INSERT INTO escrow_ledger_entries (id,liability_kind,company_id,player_uuid,amount_minor,operation_id,trade_id,occurred_at) VALUES (?,?,?,?,?,?,?,?)")){s.setString(1,UUID.randomUUID().toString());s.setString(2,kind);s.setString(3,company==null?null:company.toString());s.setString(4,player==null?null:player.toString());s.setLong(5,amount);s.setString(6,operation==null?null:operation.toString());s.setString(7,trade==null?null:trade.toString());s.setString(8,at.toString());s.executeUpdate();} }
    @Override public EscrowReconciliation reconcile(Money physical) { try(Connection c=dataSource.getConnection()){ long company=sum(c,"SELECT COALESCE(SUM(cash_minor),0) FROM company_cash_accounts"), cash=sum(c,"SELECT COALESCE(SUM(available_minor+reserved_minor),0) FROM securities_cash_accounts"), fund=sum(c,"SELECT balance_minor FROM compensation_fund WHERE singleton=1"); long ledgerCompany=sum(c,"SELECT COALESCE(SUM(amount_minor),0) FROM escrow_ledger_entries WHERE liability_kind='COMPANY_TREASURY'"), ledgerCash=sum(c,"SELECT COALESCE(SUM(amount_minor),0) FROM escrow_ledger_entries WHERE liability_kind='SECURITIES_CASH'"), ledgerFund=sum(c,"SELECT COALESCE(SUM(amount_minor),0) FROM escrow_ledger_entries WHERE liability_kind='COMPENSATION_FUND'"); if(company!=ledgerCompany||cash!=ledgerCash||fund!=ledgerFund)throw new IllegalStateException("escrow ledger does not reconcile with authoritative balances"); return new EscrowReconciliation(physical,Money.ofMinor(company),Money.ofMinor(cash),Money.ofMinor(fund),Money.zero(),Money.zero(),Money.zero()); }catch(SQLException e){throw new IllegalStateException("could not reconcile escrow",e);} }
    private static void upsert(Connection c,UUID p,long available,long reserved)throws SQLException{try(PreparedStatement read=c.prepareStatement("SELECT available_minor,reserved_minor FROM securities_cash_accounts WHERE player_uuid=?")){read.setString(1,p.toString());try(ResultSet r=read.executeQuery()){if(!r.next()){try(PreparedStatement insert=c.prepareStatement("INSERT INTO securities_cash_accounts (player_uuid,available_minor,reserved_minor) VALUES (?,?,?)")){insert.setString(1,p.toString());insert.setLong(2,available);insert.setLong(3,reserved);insert.executeUpdate();}return;}long oldAvailable=r.getLong(1),oldReserved=r.getLong(2);long newAvailable=Math.addExact(oldAvailable,available),newReserved=Math.addExact(oldReserved,reserved);try(PreparedStatement update=c.prepareStatement("UPDATE securities_cash_accounts SET available_minor=?,reserved_minor=? WHERE player_uuid=? AND available_minor=? AND reserved_minor=?")){update.setLong(1,newAvailable);update.setLong(2,newReserved);update.setString(3,p.toString());update.setLong(4,oldAvailable);update.setLong(5,oldReserved);if(update.executeUpdate()!=1)throw new SecondaryTradingRepository.OptimisticStateException("cash account changed during credit");}}}}
    private static long sum(Connection c,String sql)throws SQLException{try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){r.next();return r.getLong(1);}}
    private static void requirePositive(Money money){Objects.requireNonNull(money).requireNonNegative("amount");if(money.minorUnits()==0)throw new IllegalArgumentException("amount must be positive");}
}
