package cn.blockeco.exchange.infrastructure.sql;

import cn.blockeco.exchange.domain.company.CompanyId;
import cn.blockeco.exchange.domain.finance.ShareHolding;
import cn.blockeco.exchange.domain.money.Money;
import cn.blockeco.exchange.domain.trading.FeePolicy;
import cn.blockeco.exchange.domain.trading.LimitOrder;
import cn.blockeco.exchange.domain.trading.Trade;
import cn.blockeco.exchange.ports.SecondaryTradingRepository;
import cn.blockeco.exchange.application.*;
import java.sql.*;
import java.time.Instant;
import java.util.*;
import javax.sql.DataSource;

/** SQLite implementation.  This class intentionally owns no transaction boundary. */
public final class SqlSecondaryTradingRepository implements SecondaryTradingRepository {
    private final DataSource dataSource; private final SqlSecuritiesCashRepository cash;
    public SqlSecondaryTradingRepository(DataSource dataSource, SqlSecuritiesCashRepository cash) { this.dataSource=Objects.requireNonNull(dataSource);this.cash=Objects.requireNonNull(cash); }
    @Override public LimitOrder reserveBuy(Connection c, LimitOrder order)throws SQLException { requireTransaction(c); requireNew(order, LimitOrder.Side.BUY); LimitOrder accepted=withSequence(order,nextSequence(c)); cash.reserve(c,accepted.playerId(),accepted.reservedCash()); insertOrder(c,accepted); return accepted; }
    @Override public LimitOrder reserveSell(Connection c, LimitOrder order)throws SQLException { requireTransaction(c); requireNew(order, LimitOrder.Side.SELL); LimitOrder accepted=withSequence(order,nextSequence(c)); reserveShares(c,accepted.companyId(),accepted.playerId(),accepted.remainingShares()); insertOrder(c,accepted); return accepted; }
    @Override public boolean isListed(Connection c, LimitOrder order) throws SQLException { return findListing(c, order.stockCode()).filter(listing -> listing.companyId().equals(order.companyId())).isPresent(); }
    @Override public Optional<cn.blockeco.exchange.domain.finance.StockListing> findListing(Connection c, String code) throws SQLException {
        try (PreparedStatement s=c.prepareStatement("SELECT sl.company_id,sl.stock_code,sl.issue_reference_price_minor,sl.issued_shares,sl.listed_at FROM stock_listings sl JOIN companies c ON c.id=sl.company_id AND c.status='LISTED' WHERE sl.stock_code=?")) {
            s.setString(1,code); try(ResultSet r=s.executeQuery()) { return r.next()?Optional.of(new cn.blockeco.exchange.domain.finance.StockListing(new CompanyId(UUID.fromString(r.getString(1))),r.getString(2),Money.ofMinor(r.getLong(3)),r.getLong(4),Instant.parse(r.getString(5)))):Optional.empty(); }
        }
    }
    @Override public Optional<LimitOrder> nextCrossingMaker(Connection c, LimitOrder taker) throws SQLException {
        requireTransaction(c);
        String sql = taker.side()==LimitOrder.Side.BUY
                ? "SELECT * FROM stock_orders WHERE company_id=? AND stock_code=? AND side='SELL' AND state IN ('OPEN','PARTIALLY_FILLED') AND limit_price_minor<=? ORDER BY limit_price_minor ASC,priority_sequence ASC LIMIT 1"
                : "SELECT * FROM stock_orders WHERE company_id=? AND stock_code=? AND side='BUY' AND state IN ('OPEN','PARTIALLY_FILLED') AND limit_price_minor>=? ORDER BY limit_price_minor DESC,priority_sequence ASC LIMIT 1";
        try(PreparedStatement s=c.prepareStatement(sql)){s.setString(1,taker.companyId().value().toString());s.setString(2,taker.stockCode());s.setLong(3,taker.limitPrice().minorUnits());try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(read(r)):Optional.empty();}}
    }
    @Override public Settlement settleTrade(Connection c, Trade trade)throws SQLException {
        requireTransaction(c); LimitOrder buy=load(c,trade.buyOrderId()),sell=load(c,trade.sellOrderId()); validateFill(buy,sell,trade);
        long newFilledNotional=Math.addExact(buy.filledNotional().minorUnits(),trade.notional().minorUnits());
        long newFee=FeePolicy.cumulativeFee(Money.ofMinor(newFilledNotional),buy.feeBps()).minorUnits();
        long feeDelta=Math.subtractExact(newFee,buy.feeCharged().minorUnits());
        if(feeDelta!=trade.buyerFee().minorUnits())throw new OptimisticStateException("trade fee does not match cumulative order fee");
        long remainingBuy=Math.subtractExact(buy.remainingShares(),trade.shares()), remainingSell=Math.subtractExact(sell.remainingShares(),trade.shares());
        long newReserve=requiredReserve(remainingBuy,buy.limitPrice().minorUnits(),newFilledNotional,newFee,buy.feeBps());
        long buyerDebit=Math.addExact(trade.notional().minorUnits(),feeDelta);
        long released=Math.subtractExact(buy.reservedCash().minorUnits(),Math.addExact(buyerDebit,newReserve));
        if(released<0)throw new OptimisticStateException("buy reserve is insufficient for fill");
        insertTrade(c,trade);
        cash.adjustReservedToAvailable(c,buy.playerId(),Math.addExact(buyerDebit,released),released);
        updateSharesAfterBuy(c,buy.companyId(),buy.playerId(),trade.shares());
        updateSharesAfterSell(c,sell.companyId(),sell.playerId(),trade.shares());
        cash.creditFromTrade(c,sell.playerId(),trade.notional().minorUnits());
        cash.ledger(c,"SECURITIES_CASH",null,sell.playerId(),trade.notional().minorUnits(),null,trade.id(),trade.occurredAt());
        cash.ledger(c,"SECURITIES_CASH",null,buy.playerId(),-buyerDebit,null,trade.id(),trade.occurredAt());
        cash.creditCompensation(c,feeDelta,trade.id(),trade.occurredAt());
        updateOrder(c,buy,remainingBuy,newReserve,newFilledNotional,newFee);
        updateOrder(c,sell,remainingSell,0,0,0);
        return new Settlement(load(c,buy.id()),load(c,sell.id()),Money.ofMinor(released));
    }
    @Override public void releaseOrder(Connection c, UUID orderId, LimitOrder.State terminal)throws SQLException { requireTransaction(c); if(terminal!=LimitOrder.State.CANCELLED&&terminal!=LimitOrder.State.SELF_TRADE_PREVENTED)throw new IllegalArgumentException("terminal cancellation state required"); LimitOrder o=load(c,orderId); if(o.state()==terminal)return; if(o.state()!=LimitOrder.State.OPEN&&o.state()!=LimitOrder.State.PARTIALLY_FILLED)throw new OptimisticStateException("order is no longer active"); if(o.side()==LimitOrder.Side.BUY)cash.release(c,o.playerId(),o.reservedCash());else releaseShares(c,o.companyId(),o.playerId(),o.remainingShares()); updateTerminal(c,o,terminal); }
    @Override public void cancelTakerForSelfTrade(Connection c, UUID orderId)throws SQLException { requireTransaction(c); releaseOrder(c,orderId,LimitOrder.State.SELF_TRADE_PREVENTED); }
    @Override public Optional<LimitOrder> findOrder(Connection c, UUID id) throws SQLException { return find(c,id); }
    @Override public Optional<LimitOrder> findOrder(UUID id){try(Connection c=dataSource.getConnection()){return find(c,id);}catch(SQLException e){throw new IllegalStateException("could not find stock order",e);}}
    @Override public Optional<ShareHolding> findHolding(CompanyId company,UUID p){try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement("SELECT available_shares,reserved_shares FROM share_holdings WHERE company_id=? AND holder_uuid=?")){s.setString(1,company.value().toString());s.setString(2,p.toString());try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(new ShareHolding(company,p,r.getLong(1),r.getLong(2))):Optional.empty();}}catch(SQLException e){throw new IllegalStateException("could not find share holding",e);}}
    @Override public Money compensationFund(){try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement("SELECT balance_minor FROM compensation_fund WHERE singleton=1");ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("compensation fund missing");return Money.ofMinor(r.getLong(1));}catch(SQLException e){throw new IllegalStateException("could not read compensation fund",e);}}
    @Override public PortfolioView portfolio(UUID player){
        String sql="SELECT h.company_id,h.available_shares,h.reserved_shares,c.display_name,sl.stock_code,sl.issue_reference_price_minor FROM share_holdings h JOIN companies c ON c.id=h.company_id JOIN stock_listings sl ON sl.company_id=h.company_id WHERE h.holder_uuid=? ORDER BY sl.stock_code";
        try(Connection c=dataSource.getConnection()){long available=0,reserved=0;try(PreparedStatement a=c.prepareStatement("SELECT available_minor,reserved_minor FROM securities_cash_accounts WHERE player_uuid=?")){a.setString(1,player.toString());try(ResultSet r=a.executeQuery()){if(r.next()){available=r.getLong(1);reserved=r.getLong(2);}}}try(PreparedStatement s=c.prepareStatement(sql)){s.setString(1,player.toString());try(ResultSet r=s.executeQuery()){List<SecondaryMarketRow> holdings=new ArrayList<>();while(r.next())holdings.add(new SecondaryMarketRow(r.getString(4),r.getString(5),r.getLong(2),r.getLong(3),Money.ofMinor(latestPrice(c,r.getString(1),r.getLong(6)))));return new PortfolioView(Money.ofMinor(available),Money.ofMinor(reserved),holdings);}}}catch(SQLException e){throw failed("read portfolio",e);}
    }
    private static long latestPrice(Connection connection,String companyId,long reference)throws SQLException{Instant latestAt=null;UUID latestId=null;long latest=reference;try(PreparedStatement s=connection.prepareStatement("SELECT id,price_minor,occurred_at FROM stock_trades WHERE company_id=?")){s.setString(1,companyId);try(ResultSet r=s.executeQuery()){while(r.next()){UUID id=UUID.fromString(r.getString(1));Instant at=Instant.parse(r.getString(3));if(latestAt==null||at.isAfter(latestAt)||(at.equals(latestAt)&&id.compareTo(latestId)>0)){latestAt=at;latestId=id;latest=r.getLong(2);}}}}return latest;}
    @Override public List<OrderView> orders(UUID player,int limit){
        String sql="SELECT id,stock_code,side,limit_price_minor,original_shares,remaining_shares,reserved_cash_minor,accepted_at,state FROM stock_orders WHERE player_uuid=?";
        try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setString(1,player.toString());try(ResultSet r=s.executeQuery()){List<OrderView> out=new ArrayList<>();while(r.next())out.add(new OrderView(UUID.fromString(r.getString(1)),r.getString(2),LimitOrder.Side.valueOf(r.getString(3)),Money.ofMinor(r.getLong(4)),r.getLong(5),r.getLong(6),Money.ofMinor(r.getLong(7)),Instant.parse(r.getString(8)),LimitOrder.State.valueOf(r.getString(9))));out.sort(Comparator.comparing(OrderView::acceptedAt).reversed().thenComparing(OrderView::id,Comparator.reverseOrder()));return limit(out,limit);}}catch(SQLException e){throw failed("read player orders",e);}
    }
    @Override public List<TradeView> trades(UUID player,int limit){
        String sql="SELECT t.id,t.stock_code,CASE WHEN bo.player_uuid=? THEN 'BUY' ELSE 'SELL' END,t.shares,t.price_minor,t.notional_minor,CASE WHEN bo.player_uuid=? THEN t.buyer_fee_minor ELSE 0 END,t.occurred_at FROM stock_trades t JOIN stock_orders bo ON bo.id=t.buy_order_id JOIN stock_orders so ON so.id=t.sell_order_id WHERE bo.player_uuid=? OR so.player_uuid=?";
        try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setString(1,player.toString());s.setString(2,player.toString());s.setString(3,player.toString());s.setString(4,player.toString());try(ResultSet r=s.executeQuery()){List<TradeView> out=new ArrayList<>();while(r.next())out.add(new TradeView(UUID.fromString(r.getString(1)),r.getString(2),LimitOrder.Side.valueOf(r.getString(3)),r.getLong(4),Money.ofMinor(r.getLong(5)),Money.ofMinor(r.getLong(6)),Money.ofMinor(r.getLong(7)),Instant.parse(r.getString(8))));out.sort(Comparator.comparing(TradeView::occurredAt).reversed().thenComparing(TradeView::id,Comparator.reverseOrder()));return limit(out,limit);}}catch(SQLException e){throw failed("read player trades",e);}
    }
    @Override public List<OrderBookLevel> bids(String code,int depth){return book(code,depth,"BUY","DESC");}
    @Override public List<OrderBookLevel> asks(String code,int depth){return book(code,depth,"SELL","ASC");}
    private List<OrderBookLevel> book(String code,int depth,String side,String direction){
        String sql="SELECT o.limit_price_minor,o.remaining_shares FROM stock_orders o JOIN companies c ON c.id=o.company_id WHERE o.stock_code=? AND o.side=? AND o.state IN ('OPEN','PARTIALLY_FILLED') AND c.status='LISTED' ORDER BY o.limit_price_minor "+direction+",o.priority_sequence";
        try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setString(1,code);s.setString(2,side);try(ResultSet r=s.executeQuery()){List<OrderBookLevel> out=new ArrayList<>();long price=Long.MIN_VALUE,total=0;while(r.next()){long nextPrice=r.getLong(1),shares=r.getLong(2);if(price!=Long.MIN_VALUE&&nextPrice!=price){out.add(new OrderBookLevel(Money.ofMinor(price),total));if(out.size()==Math.max(1,Math.min(5,depth)))break;total=0;}price=nextPrice;total=Math.addExact(total,shares);}if(out.size()<Math.max(1,Math.min(5,depth))&&price!=Long.MIN_VALUE)out.add(new OrderBookLevel(Money.ofMinor(price),total));return List.copyOf(out);}}catch(SQLException e){throw failed("read order book",e);}
    }
    private static int boundHistory(int limit){return Math.max(1,Math.min(50,limit));}
    private static <T> List<T> limit(List<T> rows,int requested){return List.copyOf(rows.subList(0,Math.min(rows.size(),boundHistory(requested))));}
    private static IllegalStateException failed(String action,SQLException error){return new IllegalStateException("could not "+action,error);}
    private void insertOrder(Connection c,LimitOrder o)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO stock_orders (id,company_id,stock_code,player_uuid,side,limit_price_minor,original_shares,remaining_shares,priority_sequence,reserved_cash_minor,filled_notional_minor,fee_charged_minor,fee_bps,accepted_at,state) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){s.setString(1,o.id().toString());s.setString(2,o.companyId().value().toString());s.setString(3,o.stockCode());s.setString(4,o.playerId().toString());s.setString(5,o.side().name());s.setLong(6,o.limitPrice().minorUnits());s.setLong(7,o.originalShares());s.setLong(8,o.remainingShares());s.setLong(9,o.prioritySequence());s.setLong(10,o.reservedCash().minorUnits());s.setLong(11,o.filledNotional().minorUnits());s.setLong(12,o.feeCharged().minorUnits());s.setInt(13,o.feeBps());s.setString(14,o.acceptedAt().toString());s.setString(15,o.state().name());s.executeUpdate();}}
    private void insertTrade(Connection c,Trade t)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO stock_trades (id,company_id,stock_code,buy_order_id,sell_order_id,shares,price_minor,notional_minor,buyer_fee_minor,occurred_at) VALUES (?,?,?,?,?,?,?,?,?,?)")){s.setString(1,t.id().toString());s.setString(2,t.companyId().value().toString());s.setString(3,t.stockCode());s.setString(4,t.buyOrderId().toString());s.setString(5,t.sellOrderId().toString());s.setLong(6,t.shares());s.setLong(7,t.price().minorUnits());s.setLong(8,t.notional().minorUnits());s.setLong(9,t.buyerFee().minorUnits());s.setString(10,t.occurredAt().toString());s.executeUpdate();}}
    private void reserveShares(Connection c,CompanyId company,UUID p,long shares)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE share_holdings SET available_shares=available_shares-?,reserved_shares=reserved_shares+? WHERE company_id=? AND holder_uuid=? AND available_shares>=? AND reserved_shares<=?")){s.setLong(1,shares);s.setLong(2,shares);s.setString(3,company.value().toString());s.setString(4,p.toString());s.setLong(5,shares);s.setLong(6,Math.subtractExact(Long.MAX_VALUE,shares));if(s.executeUpdate()!=1)throw new InsufficientSharesException("insufficient shares, missing holding, or reserve overflow");}}
    private void releaseShares(Connection c,CompanyId company,UUID p,long shares)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE share_holdings SET available_shares=available_shares+?,reserved_shares=reserved_shares-? WHERE company_id=? AND holder_uuid=? AND reserved_shares>=? AND available_shares<=?")){s.setLong(1,shares);s.setLong(2,shares);s.setString(3,company.value().toString());s.setString(4,p.toString());s.setLong(5,shares);s.setLong(6,Math.subtractExact(Long.MAX_VALUE,shares));if(s.executeUpdate()!=1)throw new OptimisticStateException("share reserve state conflict or overflow");}}
    private void updateSharesAfterBuy(Connection c,CompanyId co,UUID p,long shares)throws SQLException{try(PreparedStatement read=c.prepareStatement("SELECT available_shares,reserved_shares FROM share_holdings WHERE company_id=? AND holder_uuid=?")){read.setString(1,co.value().toString());read.setString(2,p.toString());try(ResultSet r=read.executeQuery()){if(!r.next()){try(PreparedStatement insert=c.prepareStatement("INSERT INTO share_holdings (company_id,holder_uuid,available_shares,reserved_shares) VALUES (?,?,?,0)")){insert.setString(1,co.value().toString());insert.setString(2,p.toString());insert.setLong(3,shares);insert.executeUpdate();}return;}long available=r.getLong(1),reserved=r.getLong(2),next=Math.addExact(available,shares);try(PreparedStatement update=c.prepareStatement("UPDATE share_holdings SET available_shares=? WHERE company_id=? AND holder_uuid=? AND available_shares=? AND reserved_shares=?")){update.setLong(1,next);update.setString(2,co.value().toString());update.setString(3,p.toString());update.setLong(4,available);update.setLong(5,reserved);if(update.executeUpdate()!=1)throw new OptimisticStateException("buyer holding state conflict");}}}}
    private void updateSharesAfterSell(Connection c,CompanyId co,UUID p,long shares)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE share_holdings SET reserved_shares=reserved_shares-? WHERE company_id=? AND holder_uuid=? AND reserved_shares>=?")){s.setLong(1,shares);s.setString(2,co.value().toString());s.setString(3,p.toString());s.setLong(4,shares);if(s.executeUpdate()!=1)throw new OptimisticStateException("seller reserve state conflict");}}
    private void updateOrder(Connection c,LimitOrder o,long remaining,long reserve,long filled,long fee)throws SQLException{LimitOrder.State state=remaining==0?LimitOrder.State.FILLED:LimitOrder.State.PARTIALLY_FILLED;try(PreparedStatement s=c.prepareStatement("UPDATE stock_orders SET remaining_shares=?,reserved_cash_minor=?,filled_notional_minor=?,fee_charged_minor=?,state=? WHERE id=? AND remaining_shares=? AND reserved_cash_minor=? AND filled_notional_minor=? AND fee_charged_minor=? AND state=?")){s.setLong(1,remaining);s.setLong(2,reserve);s.setLong(3,filled);s.setLong(4,fee);s.setString(5,state.name());s.setString(6,o.id().toString());s.setLong(7,o.remainingShares());s.setLong(8,o.reservedCash().minorUnits());s.setLong(9,o.filledNotional().minorUnits());s.setLong(10,o.feeCharged().minorUnits());s.setString(11,o.state().name());if(s.executeUpdate()!=1)throw new OptimisticStateException("order state conflict");}}
    private void updateTerminal(Connection c,LimitOrder o,LimitOrder.State terminal)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE stock_orders SET reserved_cash_minor=0,state=? WHERE id=? AND state=?")){s.setString(1,terminal.name());s.setString(2,o.id().toString());s.setString(3,o.state().name());if(s.executeUpdate()!=1)throw new OptimisticStateException("order cancellation state conflict");}}
    private LimitOrder load(Connection c,UUID id)throws SQLException{return find(c,id).orElseThrow(()->new OptimisticStateException("stock order missing: "+id));}
    private Optional<LimitOrder> find(Connection c,UUID id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM stock_orders WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(read(r)):Optional.empty();}}}
    private static LimitOrder read(ResultSet r)throws SQLException{return new LimitOrder(UUID.fromString(r.getString("id")),new CompanyId(UUID.fromString(r.getString("company_id"))),r.getString("stock_code"),UUID.fromString(r.getString("player_uuid")),LimitOrder.Side.valueOf(r.getString("side")),Money.ofMinor(r.getLong("limit_price_minor")),r.getLong("original_shares"),r.getLong("remaining_shares"),r.getLong("priority_sequence"),Money.ofMinor(r.getLong("reserved_cash_minor")),Money.ofMinor(r.getLong("filled_notional_minor")),Money.ofMinor(r.getLong("fee_charged_minor")),r.getInt("fee_bps"),Instant.parse(r.getString("accepted_at")),LimitOrder.State.valueOf(r.getString("state")));}
    private static void requireNew(LimitOrder o, LimitOrder.Side side){if(o.side()!=side)throw new IllegalArgumentException(side.name().toLowerCase()+" order required");if(o.state()!=LimitOrder.State.OPEN||o.remainingShares()!=o.originalShares()||o.filledNotional().minorUnits()!=0||o.feeCharged().minorUnits()!=0)throw new IllegalArgumentException("only a new unfilled OPEN order may be reserved");}
    private static LimitOrder withSequence(LimitOrder o,long sequence){return new LimitOrder(o.id(),o.companyId(),o.stockCode(),o.playerId(),o.side(),o.limitPrice(),o.originalShares(),o.remainingShares(),sequence,o.reservedCash(),o.filledNotional(),o.feeCharged(),o.feeBps(),o.acceptedAt(),o.state());}
    private static long nextSequence(Connection c)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE stock_order_sequence SET last_value=last_value+1 WHERE singleton=1 AND last_value < ?")){s.setLong(1,Long.MAX_VALUE);if(s.executeUpdate()!=1)throw new ArithmeticException("stock order priority sequence overflow");}try(PreparedStatement s=c.prepareStatement("SELECT last_value FROM stock_order_sequence WHERE singleton=1");ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("stock order sequence missing");return r.getLong(1);}}
    private static void validateFill(LimitOrder b,LimitOrder s,Trade t){if(b.side()!=LimitOrder.Side.BUY||s.side()!=LimitOrder.Side.SELL||!b.companyId().equals(s.companyId())||!b.stockCode().equals(s.stockCode())||!b.companyId().equals(t.companyId())||!b.stockCode().equals(t.stockCode()))throw new OptimisticStateException("trade orders do not match");if(b.playerId().equals(s.playerId()))throw new OptimisticStateException("self trade must be prevented before settlement");if(b.state()!=LimitOrder.State.OPEN&&b.state()!=LimitOrder.State.PARTIALLY_FILLED)throw new OptimisticStateException("buy order not active");if(s.state()!=LimitOrder.State.OPEN&&s.state()!=LimitOrder.State.PARTIALLY_FILLED)throw new OptimisticStateException("sell order not active");if(t.shares()>b.remainingShares()||t.shares()>s.remainingShares()||t.price().minorUnits()>b.limitPrice().minorUnits()||t.price().minorUnits()<s.limitPrice().minorUnits())throw new OptimisticStateException("invalid fill");}
    private static long requiredReserve(long shares,long price,long filled,long fee,int bps){if(shares==0)return 0;long worst=Math.addExact(filled,Math.multiplyExact(shares,price));return Math.addExact(Math.multiplyExact(shares,price),Math.subtractExact(FeePolicy.cumulativeFee(Money.ofMinor(worst),bps).minorUnits(),fee));}
    private static void requireTransaction(Connection c)throws SQLException{if(c==null||c.getAutoCommit())throw new IllegalStateException("caller-owned transaction connection required");}
}
