package cn.blockeco.exchange.infrastructure.sql;

import cn.blockeco.exchange.domain.finance.EscrowReconciliation;
import cn.blockeco.exchange.domain.finance.SecuritiesCashAccount;
import cn.blockeco.exchange.domain.finance.SecuritiesCashOperation;
import cn.blockeco.exchange.domain.finance.SecuritiesCashOperationState;
import cn.blockeco.exchange.domain.finance.SecuritiesCashDirection;
import cn.blockeco.exchange.domain.audit.AuditEvent;
import cn.blockeco.exchange.domain.money.Money;
import cn.blockeco.exchange.ports.SecuritiesCashRepository;
import cn.blockeco.exchange.ports.SecondaryTradingRepository;
import java.sql.*;
import java.time.Instant;
import java.util.*;
import javax.sql.DataSource;

public final class SqlSecuritiesCashRepository implements SecuritiesCashRepository {
    private final DataSource dataSource;
    private final SqlAuditLog audits = new SqlAuditLog();
    public SqlSecuritiesCashRepository(DataSource dataSource) { this.dataSource = Objects.requireNonNull(dataSource); }
    @Override public Optional<SecuritiesCashAccount> find(UUID playerId) {
        try (Connection c=dataSource.getConnection(); PreparedStatement s=c.prepareStatement("SELECT available_minor,reserved_minor FROM securities_cash_accounts WHERE player_uuid=?")) { s.setString(1,playerId.toString()); try(ResultSet r=s.executeQuery()) { return r.next()?Optional.of(new SecuritiesCashAccount(playerId,Money.ofMinor(r.getLong(1)),Money.ofMinor(r.getLong(2)))):Optional.empty(); } } catch(SQLException e){throw new IllegalStateException("could not read securities cash",e);}
    }
    @Override public void creditAvailable(Connection c, UUID player, Money amount, Instant at) throws SQLException { requireTransaction(c); requirePositive(amount); upsert(c,player,amount.minorUnits(),0); ledger(c,"SECURITIES_CASH",null,player,amount.minorUnits(),null,null,at); }
    @Override public void reserve(Connection c, UUID player, Money amount) throws SQLException { requireTransaction(c); requirePositive(amount); try(PreparedStatement s=c.prepareStatement("UPDATE securities_cash_accounts SET available_minor=available_minor-?, reserved_minor=reserved_minor+? WHERE player_uuid=? AND available_minor>=? AND reserved_minor<=?")){s.setLong(1,amount.minorUnits());s.setLong(2,amount.minorUnits());s.setString(3,player.toString());s.setLong(4,amount.minorUnits());s.setLong(5,Math.subtractExact(Long.MAX_VALUE,amount.minorUnits()));if(s.executeUpdate()!=1)throw new SecondaryTradingRepository.InsufficientCashException("insufficient cash, account missing, or reserve overflow");} }
    @Override public void release(Connection c, UUID player, Money amount) throws SQLException { requireTransaction(c); requirePositive(amount); try(PreparedStatement s=c.prepareStatement("UPDATE securities_cash_accounts SET available_minor=available_minor+?, reserved_minor=reserved_minor-? WHERE player_uuid=? AND reserved_minor>=? AND available_minor<=?")){s.setLong(1,amount.minorUnits());s.setLong(2,amount.minorUnits());s.setString(3,player.toString());s.setLong(4,amount.minorUnits());s.setLong(5,Math.subtractExact(Long.MAX_VALUE,amount.minorUnits()));if(s.executeUpdate()!=1)throw new SecondaryTradingRepository.OptimisticStateException("cash reserve state conflict or overflow");} }
    @Override public void prepareOperation(Connection c, SecuritiesCashOperation o) throws SQLException { requireTransaction(c); try(PreparedStatement s=c.prepareStatement("INSERT INTO securities_cash_operations (id,player_uuid,amount_minor,direction,state,last_confirmed_external_stage,detail,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)")){s.setString(1,o.id().toString());s.setString(2,o.playerId().toString());s.setLong(3,o.amount().minorUnits());s.setString(4,o.direction().name());s.setString(5,o.state().name());s.setString(6,null);s.setString(7,o.detail());s.setString(8,o.createdAt().toString());s.setString(9,o.updatedAt().toString());s.executeUpdate();} audit(c,o,"PREPARED",o.detail(),o.createdAt()); }
    @Override public void transitionOperation(Connection c, UUID id, SecuritiesCashOperationState expected, SecuritiesCashOperationState state, SecuritiesCashOperationState stage, String detail, Instant at) throws SQLException { requireTransaction(c); SecuritiesCashOperation current=findForUpdate(c,id); if(current.state()!=expected)throw new IllegalStateException("cash operation state conflict: "+id); if(!legalTransition(current.direction(),expected,state,stage))throw new IllegalArgumentException("illegal cash operation transition: "+expected+" -> "+state); try(PreparedStatement s=c.prepareStatement("UPDATE securities_cash_operations SET state=?,last_confirmed_external_stage=?,detail=?,updated_at=? WHERE id=? AND state=?")){s.setString(1,state.name());s.setString(2,stage==null?null:stage.name());s.setString(3,detail);s.setString(4,at.toString());s.setString(5,id.toString());s.setString(6,expected.name());if(s.executeUpdate()!=1)throw new IllegalStateException("cash operation state conflict: "+id);} audit(c,current,state.name(),detail,at); }
    @Override public void completeDeposit(Connection c,SecuritiesCashOperation o,Instant at)throws SQLException { requireTransaction(c); upsert(c,o.playerId(),o.amount().minorUnits(),0); ledger(c,"SECURITIES_CASH",null,o.playerId(),o.amount().minorUnits(),o.id(),null,at); transitionOperation(c,o.id(),SecuritiesCashOperationState.ESCROW_DEPOSITED,SecuritiesCashOperationState.COMPLETED,SecuritiesCashOperationState.ESCROW_DEPOSITED,"local deposit credit completed",at); }
    @Override public void completeWithdrawal(Connection c,SecuritiesCashOperation o,Instant at)throws SQLException { requireTransaction(c); try(PreparedStatement s=c.prepareStatement("UPDATE securities_cash_accounts SET reserved_minor=reserved_minor-? WHERE player_uuid=? AND reserved_minor>=?")){s.setLong(1,o.amount().minorUnits());s.setString(2,o.playerId().toString());s.setLong(3,o.amount().minorUnits());if(s.executeUpdate()!=1)throw new IllegalStateException("withdraw reserve missing");} ledger(c,"SECURITIES_CASH",null,o.playerId(),-o.amount().minorUnits(),o.id(),null,at); transitionOperation(c,o.id(),SecuritiesCashOperationState.PLAYER_DEPOSITED,SecuritiesCashOperationState.COMPLETED,SecuritiesCashOperationState.PLAYER_DEPOSITED,"local withdrawal debit completed",at); }
    @Override public Optional<SecuritiesCashOperation> findOperation(UUID id){return findOps("SELECT * FROM securities_cash_operations WHERE id=?",id.toString()).stream().findFirst();}
    @Override public Optional<SecuritiesCashOperation> findActiveOperation(UUID player){return findOps("SELECT * FROM securities_cash_operations WHERE player_uuid=? AND state NOT IN ('COMPLETED','FAILED')",player.toString()).stream().findFirst();}
    @Override public List<SecuritiesCashOperation> findRecoveryCandidates(){return findOps("SELECT * FROM securities_cash_operations WHERE state NOT IN ('COMPLETED','FAILED')",null);}
    private List<SecuritiesCashOperation> findOps(String sql,String arg){try(Connection c=dataSource.getConnection()){return findOps(c,sql,arg);}catch(SQLException e){throw new IllegalStateException("could not read cash operations",e);}}
    /** Caller already owns the pooled connection (notably reconciliation): never borrow a nested one. */
    private static List<SecuritiesCashOperation> findOps(Connection c,String sql,String arg)throws SQLException{try(PreparedStatement s=c.prepareStatement(sql)){if(arg!=null)s.setString(1,arg);try(ResultSet r=s.executeQuery()){List<SecuritiesCashOperation> out=new ArrayList<>();while(r.next())out.add(operation(r));return out;}}}
    private static SecuritiesCashOperation operation(ResultSet r)throws SQLException{return new SecuritiesCashOperation(UUID.fromString(r.getString("id")),UUID.fromString(r.getString("player_uuid")),Money.ofMinor(r.getLong("amount_minor")),SecuritiesCashDirection.valueOf(r.getString("direction")),SecuritiesCashOperationState.valueOf(r.getString("state")),r.getString("last_confirmed_external_stage")==null?null:SecuritiesCashOperationState.valueOf(r.getString("last_confirmed_external_stage")),r.getString("detail"),Instant.parse(r.getString("created_at")),Instant.parse(r.getString("updated_at")));}
    private static boolean legalTransition(SecuritiesCashDirection direction,SecuritiesCashOperationState from,SecuritiesCashOperationState to,SecuritiesCashOperationState stage){if(to==SecuritiesCashOperationState.AMBIGUOUS)return legalAmbiguousTransition(direction,from,stage); if(direction==SecuritiesCashDirection.DEPOSIT)return (from==SecuritiesCashOperationState.PREPARED&&to==SecuritiesCashOperationState.PLAYER_WITHDRAWN&&stage==to)||(from==SecuritiesCashOperationState.PLAYER_WITHDRAWN&&to==SecuritiesCashOperationState.ESCROW_DEPOSITED&&stage==to)||(from==SecuritiesCashOperationState.ESCROW_DEPOSITED&&to==SecuritiesCashOperationState.COMPLETED&&stage==from)||(from==SecuritiesCashOperationState.PREPARED&&to==SecuritiesCashOperationState.FAILED&&stage==null); return (from==SecuritiesCashOperationState.PREPARED&&to==SecuritiesCashOperationState.ESCROW_WITHDRAWN&&stage==to)||(from==SecuritiesCashOperationState.ESCROW_WITHDRAWN&&to==SecuritiesCashOperationState.PLAYER_DEPOSITED&&stage==to)||(from==SecuritiesCashOperationState.PLAYER_DEPOSITED&&to==SecuritiesCashOperationState.COMPLETED&&stage==from)||(from==SecuritiesCashOperationState.PREPARED&&to==SecuritiesCashOperationState.FAILED&&stage==null);}
    private static boolean legalAmbiguousTransition(SecuritiesCashDirection direction,SecuritiesCashOperationState from,SecuritiesCashOperationState stage){if(direction==SecuritiesCashDirection.DEPOSIT){if(from==SecuritiesCashOperationState.PREPARED)return stage==null||stage==SecuritiesCashOperationState.PLAYER_WITHDRAWN;if(from==SecuritiesCashOperationState.PLAYER_WITHDRAWN)return stage==from||stage==SecuritiesCashOperationState.ESCROW_DEPOSITED;return from==SecuritiesCashOperationState.ESCROW_DEPOSITED&&stage==from;}if(from==SecuritiesCashOperationState.PREPARED)return stage==null||stage==SecuritiesCashOperationState.ESCROW_WITHDRAWN;if(from==SecuritiesCashOperationState.ESCROW_WITHDRAWN)return stage==from||stage==SecuritiesCashOperationState.PLAYER_DEPOSITED;return from==SecuritiesCashOperationState.PLAYER_DEPOSITED&&stage==from;}
    private static SecuritiesCashOperation findForUpdate(Connection c,UUID id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT * FROM securities_cash_operations WHERE id=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("cash operation missing: "+id);return operation(r);}}}
    private void audit(Connection c,SecuritiesCashOperation o,String state,String detail,Instant at)throws SQLException{audits.append(c,new AuditEvent(UUID.randomUUID(),Optional.empty(),Optional.of(o.playerId()),"SECURITIES_CASH_"+state,Map.of("operationId",o.id().toString(),"direction",o.direction().name(),"amountMinor",o.amount().minorUnits(),"detail",detail==null?"":detail),at));}
    void adjustReservedToAvailable(Connection c, UUID player, long debitReserved, long creditAvailable) throws SQLException { requireTransaction(c); if(debitReserved<0||creditAvailable<0||debitReserved<creditAvailable)throw new IllegalArgumentException("invalid cash settlement adjustment"); try(PreparedStatement s=c.prepareStatement("UPDATE securities_cash_accounts SET reserved_minor=reserved_minor-?, available_minor=available_minor+? WHERE player_uuid=? AND reserved_minor>=? AND available_minor<=?")){s.setLong(1,debitReserved);s.setLong(2,creditAvailable);s.setString(3,player.toString());s.setLong(4,debitReserved);s.setLong(5,Math.subtractExact(Long.MAX_VALUE,creditAvailable));if(s.executeUpdate()!=1)throw new SecondaryTradingRepository.OptimisticStateException("buyer reserve state conflict or overflow");} }
    void creditFromTrade(Connection c, UUID player, long amount) throws SQLException { requireTransaction(c); if(amount<0)throw new IllegalArgumentException("negative credit"); upsert(c,player,amount,0); }
    void creditCompensation(Connection c,long amount,UUID trade,Instant at)throws SQLException { requireTransaction(c); if(amount==0)return; if(amount<0)throw new IllegalArgumentException("negative compensation credit");try(PreparedStatement s=c.prepareStatement("UPDATE compensation_fund SET balance_minor=balance_minor+? WHERE singleton=1 AND balance_minor<=?")){s.setLong(1,amount);s.setLong(2,Math.subtractExact(Long.MAX_VALUE,amount));if(s.executeUpdate()!=1)throw new ArithmeticException("compensation fund overflow or missing");}ledger(c,"COMPENSATION_FUND",null,null,amount,null,trade,at); }
    void ledger(Connection c,String kind,UUID company,UUID player,long amount,UUID operation,UUID trade,Instant at)throws SQLException { requireTransaction(c); if(amount==0)return;try(PreparedStatement s=c.prepareStatement("INSERT INTO escrow_ledger_entries (id,liability_kind,company_id,player_uuid,amount_minor,operation_id,trade_id,occurred_at) VALUES (?,?,?,?,?,?,?,?)")){s.setString(1,UUID.randomUUID().toString());s.setString(2,kind);s.setString(3,company==null?null:company.toString());s.setString(4,player==null?null:player.toString());s.setLong(5,amount);s.setString(6,operation==null?null:operation.toString());s.setString(7,trade==null?null:trade.toString());s.setString(8,at.toString());s.executeUpdate();} }
    @Override public EscrowReconciliation reconcile(Money physical) { try(Connection c=dataSource.getConnection()){ long company=sumColumn(c,"SELECT cash_minor FROM company_cash_accounts"), cash=sumCash(c), fund=sumColumn(c,"SELECT balance_minor FROM compensation_fund WHERE singleton=1"); long ledgerCompany=sumColumn(c,"SELECT amount_minor FROM escrow_ledger_entries WHERE liability_kind='COMPANY_TREASURY'"), ledgerCash=sumColumn(c,"SELECT amount_minor FROM escrow_ledger_entries WHERE liability_kind='SECURITIES_CASH'"), ledgerFund=sumColumn(c,"SELECT amount_minor FROM escrow_ledger_entries WHERE liability_kind='COMPENSATION_FUND'"); if(company!=ledgerCompany||cash!=ledgerCash||fund!=ledgerFund)throw new IllegalStateException("escrow ledger does not reconcile with authoritative balances"); long inbound=0,outbound=0,uncertain=0; for(SecuritiesCashOperation o:findOps(c,"SELECT * FROM securities_cash_operations WHERE state NOT IN ('COMPLETED','FAILED')",null)){if(o.direction()==SecuritiesCashDirection.DEPOSIT&&o.lastConfirmedExternalStage()==SecuritiesCashOperationState.ESCROW_DEPOSITED)inbound=Math.addExact(inbound,o.amount().minorUnits());if(o.direction()==SecuritiesCashDirection.WITHDRAW&&(o.lastConfirmedExternalStage()==SecuritiesCashOperationState.ESCROW_WITHDRAWN||o.lastConfirmedExternalStage()==SecuritiesCashOperationState.PLAYER_DEPOSITED))outbound=Math.addExact(outbound,o.amount().minorUnits());if(o.state()==SecuritiesCashOperationState.AMBIGUOUS)uncertain=Math.addExact(uncertain,o.amount().minorUnits());} return new EscrowReconciliation(physical,Money.ofMinor(company),Money.ofMinor(cash),Money.ofMinor(fund),Money.ofMinor(inbound),Money.ofMinor(outbound),Money.ofMinor(uncertain)); }catch(SQLException e){throw new IllegalStateException("could not reconcile escrow",e);} }
    private static void upsert(Connection c,UUID p,long available,long reserved)throws SQLException{try(PreparedStatement read=c.prepareStatement("SELECT available_minor,reserved_minor FROM securities_cash_accounts WHERE player_uuid=?")){read.setString(1,p.toString());try(ResultSet r=read.executeQuery()){if(!r.next()){try(PreparedStatement insert=c.prepareStatement("INSERT INTO securities_cash_accounts (player_uuid,available_minor,reserved_minor) VALUES (?,?,?)")){insert.setString(1,p.toString());insert.setLong(2,available);insert.setLong(3,reserved);insert.executeUpdate();}return;}long oldAvailable=r.getLong(1),oldReserved=r.getLong(2);long newAvailable=Math.addExact(oldAvailable,available),newReserved=Math.addExact(oldReserved,reserved);try(PreparedStatement update=c.prepareStatement("UPDATE securities_cash_accounts SET available_minor=?,reserved_minor=? WHERE player_uuid=? AND available_minor=? AND reserved_minor=?")){update.setLong(1,newAvailable);update.setLong(2,newReserved);update.setString(3,p.toString());update.setLong(4,oldAvailable);update.setLong(5,oldReserved);if(update.executeUpdate()!=1)throw new SecondaryTradingRepository.OptimisticStateException("cash account changed during credit");}}}}
    private static long sumColumn(Connection c,String sql)throws SQLException{long total=0;try(PreparedStatement s=c.prepareStatement(sql);ResultSet rows=s.executeQuery()){while(rows.next())total=Math.addExact(total,rows.getLong(1));return total;}}
    private static long sumCash(Connection c)throws SQLException{long total=0;try(PreparedStatement s=c.prepareStatement("SELECT available_minor,reserved_minor FROM securities_cash_accounts");ResultSet rows=s.executeQuery()){while(rows.next())total=Math.addExact(total,Math.addExact(rows.getLong(1),rows.getLong(2)));return total;}}
    private static void requirePositive(Money money){Objects.requireNonNull(money).requireNonNegative("amount");if(money.minorUnits()==0)throw new IllegalArgumentException("amount must be positive");}
    private static void requireTransaction(Connection c)throws SQLException{if(c==null||c.getAutoCommit())throw new IllegalStateException("caller-owned transaction connection required");}
}
