name: BlockecoExchange
version: '${version}'
main: cn.blockeco.exchange.BlockecoPlugin
api-version: '1.21'
softdepend: [Vault, VaultUnlocked]
commands:
  company:
    description: 管理 Blockeco 公司
    usage: /company <创建|信息|恢复>
permissions:
  blockeco.company.create:
    default: true
  blockeco.company.info:
    default: true
  blockeco.admin.recovery:
    default: op
