package cn.blockeco.exchange.paper;

import cn.blockeco.exchange.application.CompanyCapitalActionService;
import cn.blockeco.exchange.application.CompanyQueryService;
import cn.blockeco.exchange.domain.money.Money;
import cn.blockeco.exchange.ports.MainThreadExecutor;
import java.math.BigDecimal;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.Executor;
import java.util.function.BooleanSupplier;
import net.kyori.adventure.text.Component;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.inventory.*;
import org.bukkit.inventory.*;
import org.bukkit.plugin.java.JavaPlugin;

/** Founder-only native GUI for the two announced capital actions. Monetary execution stays in the application service. */
public final class CapitalActionGuiController implements Listener, CompanyGuiOpener {
    private final JavaPlugin plugin; private final CompanyCapitalActionService actions; private final CompanyQueryService companies; private final MainThreadExecutor main; private final Executor worker; private final BooleanSupplier accepting; private final int scale; private final CompanyGuiOpener back; private final StockGuiItemFactory items;
    private final Map<UUID, Session> sessions=new ConcurrentHashMap<>(); private final Set<UUID> replacing=ConcurrentHashMap.newKeySet(); private final Set<UUID> busy=ConcurrentHashMap.newKeySet();
    public CapitalActionGuiController(JavaPlugin plugin, CompanyCapitalActionService actions, CompanyQueryService companies, MainThreadExecutor main, Executor worker, BooleanSupplier accepting, int scale, CompanyGuiOpener back){this.plugin=plugin;this.actions=actions;this.companies=companies;this.main=main;this.worker=worker;this.accepting=accepting;this.scale=scale;this.back=back;this.items=new StockGuiItemFactory(plugin);}
    @Override public void open(Player p){ if(!ready(p))return; if(!p.hasPermission("blockeco.company.capital-actions")){p.sendMessage(Component.text("你没有权限。"));return;} Session s=new Session(UUID.randomUUID(),p.getUniqueId(),null,new Money[0]);sessions.put(p.getUniqueId(),s); render(p,s); }
    private void render(Player p,Session s){ Inventory i=inv(s,"Bloeco-Stock 资本动作");fill(i); put(i,20,Material.GOLD_INGOT,"buyback","发起股份回购","股东自愿接受；公告满 12 小时后执行");put(i,22,Material.IRON_INGOT,"accept-list","接受公司回购","仅卖出你自愿出售的股份");put(i,24,Material.EMERALD,"cashout","发起创始人套现","公告满 12 小时后才可执行；受管理员单次上限限制");put(i,31,Material.CLOCK,"noop","公告与恢复","发生不确定 Vault 入账时只能由管理员人工核对，不会自动重打款");put(i,49,Material.ARROW,"back","返回公司中心","返回上一级");openInv(p,i);}
    @EventHandler public void click(InventoryClickEvent e){if(!(e.getView().getTopInventory().getHolder() instanceof Holder h)||!(e.getWhoClicked() instanceof Player p)||!same(p,h.s))return;e.setCancelled(true);if(e.getRawSlot()<0||e.getRawSlot()>=e.getView().getTopInventory().getSize())return;String a=items.action(e.getCurrentItem());if(a==null)return;switch(a){case "back"->back.open(p);case "buyback"->input(p,h.s,Kind.BUYBACK,"输入回购预算","从公司账户预留，正数金额");case "cashout"->input(p,h.s,Kind.CASHOUT,"输入套现金额","管理员可配置单次上限，0 表示禁用");case "confirm"->confirm(p,h.s);case "cancel"->render(p,h.s);case "accept-list"->p.sendMessage(Component.text("回购接受列表正在接入，请稍后刷新。"));default->{}}}
    @EventHandler public void drag(InventoryDragEvent e){if(e.getInventory().getHolder() instanceof Holder)e.setCancelled(true);}
    @EventHandler public void close(InventoryCloseEvent e){if(e.getInventory().getHolder() instanceof Holder h&&e.getPlayer() instanceof Player p&&!replacing.contains(p.getUniqueId())&&same(p,h.s))sessions.remove(p.getUniqueId(),h.s);}
    private void input(Player p,Session s,Kind kind,String title,String hint){TextInputGui.open(plugin,p,title,raw->{try{Money amount=Money.fromMajor(new BigDecimal(raw),scale);if(amount.minorUnits()<=0)throw new IllegalArgumentException();if(kind==Kind.BUYBACK){Session next=s.next(kind,amount);sessions.put(p.getUniqueId(),next);TextInputGui.open(plugin,p,"输入回购每股价格",price->{try{Money unit=Money.fromMajor(new BigDecimal(price),scale);if(unit.minorUnits()<=0)throw new IllegalArgumentException();Session ready=next.next(kind,amount,unit);sessions.put(p.getUniqueId(),ready);confirmPage(p,ready);}catch(RuntimeException x){p.sendMessage(Component.text("每股价格格式不正确。"));}});}else{Session ready=s.next(kind,amount);sessions.put(p.getUniqueId(),ready);confirmPage(p,ready);}}catch(RuntimeException x){p.sendMessage(Component.text("金额格式不正确。"));}});}
    private void confirmPage(Player p,Session s){Inventory i=inv(s,"确认资本动作");fill(i);String line=s.kind==Kind.BUYBACK?"预算 "+fmt(s.amount)+"；每股 "+fmt(s.price):"套现 "+fmt(s.amount)+"；12 小时公告期后才会调用 Vault";put(i,22,Material.BOOK,"noop","请确认",line);put(i,29,Material.LIME_WOOL,"confirm","确认发布公告","发布后可在交易所公告查看");put(i,33,Material.RED_WOOL,"cancel","取消","不执行任何操作");openInv(p,i);}
    private void confirm(Player p,Session s){if(s.kind==null||s.amount==null||!busy.add(p.getUniqueId()))return;companies.findByFounder(p.getUniqueId()).whenComplete((company,error)->worker.execute(()->{UUID id=null;try{if(error!=null||company.isEmpty())throw new IllegalStateException();id=s.kind==Kind.BUYBACK?actions.announceBuyback(p.getUniqueId(),company.get().id(),s.amount,s.price,"gui-buyback:"+s.correlation):actions.announceFounderCashOut(p.getUniqueId(),company.get().id(),s.amount,"gui-cashout:"+s.correlation);}catch(RuntimeException ignored){}UUID result=id;main.submit(()->{busy.remove(p.getUniqueId());if(result==null){p.sendMessage(Component.text("资本动作未发布：请检查公司状态、资金或管理员套现上限。"));return null;}sessions.remove(p.getUniqueId(),s);p.sendMessage(Component.text("资本动作公告已发布（12 小时后可执行）："+result));back.open(p);return null;});}));}
    private boolean ready(Player p){if(accepting.getAsBoolean())return true;p.sendMessage(Component.text("Bloeco-Stock 正在初始化，请稍后再试。"));return false;}private boolean same(Player p,Session s){return s.owner.equals(p.getUniqueId())&&s.equals(sessions.get(p.getUniqueId()));}private Inventory inv(Session s,String title){return Bukkit.createInventory(new Holder(s),54,Component.text(title));}private void fill(Inventory i){for(int x=0;x<i.getSize();x++)i.setItem(x,items.filler());}private void put(Inventory i,int slot,Material m,String a,String n,String l){i.setItem(slot,items.action(m,a,Component.text(n),List.of(Component.text(l))));}private void openInv(Player p,Inventory i){GuiTransitions.defer(a->Bukkit.getScheduler().runTask(plugin,a),()->{replacing.add(p.getUniqueId());try{p.openInventory(i);}finally{replacing.remove(p.getUniqueId());}});}private String fmt(Money m){return m.toMajor(scale).toPlainString();}
    private enum Kind{BUYBACK,CASHOUT} private static final class Session{final UUID id,owner,correlation;final Kind kind;final Money amount,price;Session(UUID id,UUID owner,Kind kind,Money...value){this(id,owner,UUID.randomUUID(),kind,value);}Session(UUID id,UUID owner,UUID correlation,Kind kind,Money...value){this.id=id;this.owner=owner;this.correlation=correlation;this.kind=kind;this.amount=value.length>0?value[0]:null;this.price=value.length>1?value[1]:null;}Session next(Kind k,Money...value){return new Session(UUID.randomUUID(),owner,correlation,k,value);}}private record Holder(Session s) implements InventoryHolder{@Override public Inventory getInventory(){return null;}}
}
