/* Isolated original-client acceptance.  Fixed loopback ports deliberately exclude 25565. */
import assert from 'node:assert/strict'
import net from 'node:net'
import { readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { DatabaseSync } from 'node:sqlite'
import mineflayer from 'mineflayer'

const HOST='127.0.0.1', GAME_PORT=25566, RCON_PORT=25567, timeoutMs=25_000
const sleep=ms=>new Promise(r=>setTimeout(r,ms)), phase=process.env.QA_CLOCK_PHASE??'OPEN'
const player=`Bluechip${phase}`, dbPath='../plugins/BlockStock/blockeco.db'
function pkt(id,type,body){const q=Buffer.from(body),p=Buffer.alloc(14+q.length);p.writeInt32LE(10+q.length);p.writeInt32LE(id,4);p.writeInt32LE(type,8);q.copy(p,12);return p}
function rcon(command){const password=/^rcon.password=(.*)$/m.exec(readFileSync('../server.properties','utf8'))?.[1];assert.ok(password,'QA RCON password missing');return new Promise((resolve,reject)=>{const s=net.createConnection({host:HOST,port:RCON_PORT});let authed=false,b=Buffer.alloc(0);s.setTimeout(timeoutMs,()=>reject(new Error(`RCON timeout: ${command}`)));s.on('connect',()=>s.write(pkt(101,3,password)));s.on('data',d=>{b=Buffer.concat([b,d]);if(b.length<4||b.length<b.readInt32LE(0)+4)return;const id=b.readInt32LE(4),body=b.subarray(12,b.readInt32LE(0)+2).toString();if(!authed){if(id===-1)return reject(new Error('QA RCON auth failed'));authed=true;s.write(pkt(102,2,command));return}s.end();resolve(body)});s.on('error',reject)})}
function openDb(){return new DatabaseSync(dbPath,{readOnly:true})} function one(d,sql,...v){const r=d.prepare(sql).get(...v);return r&&Object.values(r)[0]}
function offlineUuid(username){const b=createHash('md5').update(`OfflinePlayer:${username}`).digest();b[6]=(b[6]&0x0f)|0x30;b[8]=(b[8]&0x3f)|0x80;const h=b.toString('hex');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`}
function title(w){return typeof w?.title==='string'?w.title:JSON.stringify(w?.title??'')} function name(i){return i?.displayName??i?.name??''}
function connect(){return new Promise((resolve,reject)=>{const b=mineflayer.createBot({host:HOST,port:GAME_PORT,username:player,auth:'offline',version:'1.21.4'});const timer=setTimeout(()=>{b.quit('spawn timeout');reject(new Error('Mineflayer did not reach spawn within QA timeout'))},timeoutMs);b.once('spawn',()=>{clearTimeout(timer);resolve(b)});b.once('kicked',r=>{clearTimeout(timer);reject(new Error(`kicked: ${JSON.stringify(r)}`))});b.once('error',e=>{clearTimeout(timer);reject(e)})})}
async function waitWindow(b,expected,seq=-1){if(b.windowSequence>seq&&title(b.currentWindow).includes(expected))return b.currentWindow;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{b.off('windowOpen',opened);reject(new Error(`window timeout ${expected}; current=${title(b.currentWindow)}`))},timeoutMs);const opened=w=>{if(!title(w).includes(expected))return;clearTimeout(timer);b.off('windowOpen',opened);resolve(w)};b.on('windowOpen',opened)})}
async function click(b,slot,expected){const next=waitWindow(b,expected,b.windowSequence);await sleep(150);try{await b.clickWindow(slot,0,0)}catch{}const w=await next;await sleep(250);return w}
async function confirm(b){await sleep(150);try{await b.clickWindow(29,0,0)}catch{}await sleep(1200)}
async function input(b,text,expected){for(let i=1;i<=text.length;i++){b._client.write('name_item',{name:text.slice(0,i)});await sleep(45)}return click(b,2,expected)} async function home(b){b.chat('/stock');return waitWindow(b,'BlockStock',-1)}
function componentText(i){return JSON.stringify(i?.nbt??i?.components??i?.name??'')} function novaSlot(w){return w.slots.slice(0,10).findIndex(i=>componentText(i).includes('NOVA'))} function ten(w){const a=w.slots.slice(0,10).filter(Boolean);assert.equal(a.length,10,`market count=${a.length}`);for(const code of ['NOVA','AURORA','TERRAN','SKYLINE','IRONWOOD','LUMEN','RIVERMINT','ORBITAL','CINDER','VERDANT'])assert.ok(a.some(i=>componentText(i).includes(code)),`missing configured ticker ${code} in vanilla market GUI`)} function five(w){for(const s of [10,11,12,13,14])assert.ok(componentText(w.slots[s]).includes(`卖${s-9}`),`missing real ask level ${s-9}`);for(const s of [28,29,30,31,32])assert.ok(componentText(w.slots[s]).includes(`买${s-27}`),`missing real bid level ${s-27}`)}
async function deposit(b){await home(b);await click(b,13,'证券账户');await click(b,29,'输入金额');await input(b,'10000','确认执行');await confirm(b)}
async function buy(b){await home(b);const m=await click(b,11,'市场');ten(m);const slot=novaSlot(m);assert.ok(slot>=0,'NOVA must be selectable in the vanilla market GUI');const detail=await click(b,slot,'BlockStock NOVA');if(phase==='OPEN')five(detail);await click(b,48,'输入正整数股数');await input(b,'10','输入限价');await input(b,'12.00','确认执行');await confirm(b)}
async function gui(){await rcon(`op ${player}`);await rcon(`eco give ${player} 1000000`);const b=await connect();const playerId=offlineUuid(player);b.windowSequence=0;b.on('windowOpen',w=>{b.windowSequence++;console.log(`BLUECHIP_WINDOW|${title(w)}`)});b.on('messagestr',m=>console.log(`BLUECHIP_CHAT|${m}`));try{let d=openDb(),trades=one(d,"SELECT COUNT(*) FROM stock_trades WHERE stock_code='NOVA'"),preTrades=one(d,"SELECT COUNT(*) FROM stock_trades t JOIN stock_orders o ON o.id=t.buy_order_id WHERE o.player_uuid=?",offlineUuid('BluechipPREOPEN'));d.close();await deposit(b);await buy(b);await sleep(1500);d=openDb();if(phase==='OPEN'){assert.ok(preTrades>0,'PREOPEN order must receive an opening-session fill');assert.ok(one(d,"SELECT COUNT(*) FROM stock_trades WHERE stock_code='NOVA'")>trades,'open GUI buy must receive a real partial or full trade');assert.ok(one(d,"SELECT COALESCE(available_shares+reserved_shares,0) FROM share_holdings h JOIN stock_listings l ON l.company_id=h.company_id WHERE h.holder_uuid=? AND l.stock_code='NOVA'",playerId)>0,'open GUI buy must credit actual filled NOVA shares');assert.ok(one(d,'SELECT available_minor+reserved_minor FROM securities_cash_accounts WHERE player_uuid=?',playerId)<1000000,'open GUI buy must debit or reserve securities cash by its actual fill');await rcon('stockadmin bluechip event market 100');await home(b);const n=await click(b,33,'市场快讯');assert.ok(n.slots.some(i=>componentText(i).includes('大盘')||componentText(i).includes('市场')),'admin event must be visible in GUI news');console.log('BLUECHIP_GUI_PASS|OPEN|ten|five|deposit|partial-trade|holding|cash|news')}else{assert.equal(one(d,"SELECT COUNT(*) FROM stock_orders WHERE player_uuid=? AND stock_code='NOVA' AND state IN ('OPEN','PARTIALLY_FILLED')",playerId),1,`${phase} order must queue or remain partially filled`);assert.equal(one(d,"SELECT COUNT(*) FROM stock_trades WHERE stock_code='NOVA'"),trades,`${phase} cannot match`);console.log(`BLUECHIP_GUI_PASS|${phase}|deposit|queued`)}d.close()}finally{b.quit('isolated QA complete')}}
function ledger(){const d=openDb();try{assert.equal(one(d,'SELECT COUNT(*) FROM bluechip_companies'),10,'ten bluechips');assert.equal(one(d,'SELECT COUNT(*) FROM securities_cash_accounts WHERE available_minor<0 OR reserved_minor<0'),0,'negative cash');assert.equal(one(d,'SELECT COUNT(*) FROM share_holdings WHERE available_shares<0 OR reserved_shares<0'),0,'negative holdings');assert.equal(one(d,"SELECT COUNT(*) FROM bluechip_bootstrap_funding WHERE state='COMPLETED'"),1,'bootstrap escrow funding');assert.equal(one(d,'SELECT COUNT(*) FROM (SELECT sl.company_id FROM stock_listings sl JOIN bluechip_companies bc ON bc.company_id=sl.company_id LEFT JOIN share_holdings h ON h.company_id=sl.company_id GROUP BY sl.company_id,sl.issued_shares HAVING COALESCE(SUM(h.available_shares+h.reserved_shares),0)<>sl.issued_shares)'),0,'share conservation');assert.equal(one(d,"SELECT COUNT(*) FROM (SELECT company_id,trading_day,COUNT(*) n FROM market_candles GROUP BY company_id,trading_day HAVING n>1)"),0,'candle idempotency');assert.equal(one(d,"SELECT COUNT(*) FROM (SELECT company_id,dividend_at,COUNT(*) n FROM dividend_runs GROUP BY company_id,dividend_at HAVING n>1)"),0,'dividend idempotency');assert.ok(one(d,"SELECT COUNT(*) FROM bluechip_events WHERE scope='MARKET'")>=1,'persisted admin event');assert.ok(one(d,"SELECT COUNT(*) FROM stock_trades WHERE stock_code='NOVA'")>=15,'preopen, open and postclose orders must each receive real fills');assert.ok(one(d,'SELECT COUNT(*) FROM market_candles')>=10,'postclose candles');assert.equal(one(d,"SELECT COUNT(*) FROM dividend_runs WHERE state='COMPLETED'"),10,'each fixture-driven 15-day dividend ran once');assert.equal(one(d,'SELECT COUNT(*) FROM dividend_runs WHERE total_payout_minor<0'),0,'negative payout');console.log(`BLUECHIP_LEDGER_PASS|liabilities_minor=${one(d,'SELECT COALESCE(SUM(available_minor+reserved_minor),0) FROM securities_cash_accounts')}`)}finally{d.close()}}
if(process.argv.includes('--ledger'))ledger();else gui().catch(e=>{console.error(`BLUECHIP_GUI_FAIL|${e.stack??e.message}`);process.exitCode=1})
