CREATE TABLE bluechip_bootstrap_funding (
  id TEXT PRIMARY KEY,
  system_account_uuid TEXT NOT NULL,
  amount_minor INTEGER NOT NULL CHECK (amount_minor > 0),
  state TEXT NOT NULL CHECK (state IN ('PREPARED','SOURCE_CREDIT_REQUESTED','SOURCE_CREDITED','SOURCE_DEBIT_REQUESTED','SOURCE_DEBITED','ESCROW_DEPOSIT_REQUESTED','ESCROW_DEPOSITED','COMPLETED','AMBIGUOUS')),
  detail TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
