package cn.blockeco.exchange.infrastructure.sql;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import cn.blockeco.exchange.application.Fixtures;
import cn.blockeco.exchange.domain.company.CompanyStatus;
import cn.blockeco.exchange.domain.finance.StockListing;
import cn.blockeco.exchange.domain.finance.PublicOfferingView;
import cn.blockeco.exchange.domain.money.Money;
import java.nio.file.*;
import java.time.Instant;
import java.sql.Connection;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.UUID;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.Test;

class SqlPrimaryOfferingRepositoryTest {
 @Test void ipo_completion_overflow_rolls_back_cash_ledger_holding_company_and_operation() throws Exception { Path file=Files.createTempFile("ipo-overflow-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate();var company=Fixtures.company(db,100);var repo=new SqlPrimaryOfferingRepository(db.dataSource());var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(100),Instant.parse("2026-08-22T12:00:00Z"));UUID subscription=UUID.randomUUID(),player=UUID.randomUUID();db.inTransaction(c->{repo.announce(c,offer);repo.prepareSubscription(c,subscription,offer,player,1,offer.opensAt());repo.markWithdrawn(c,subscription,offer.opensAt());repo.markEscrowDeposited(c,subscription,offer.opensAt());try(var s=c.prepareStatement("UPDATE company_cash_accounts SET cash_minor=? WHERE company_id=?")){s.setLong(1,Long.MAX_VALUE);s.setString(2,company.value().toString());s.executeUpdate();}return null;});assertThatThrownBy(()->db.inTransaction(c->{repo.completeSubscription(c,subscription,offer.opensAt());return null;})).isInstanceOf(ArithmeticException.class);assertThat(number(db,"SELECT cash_minor FROM company_cash_accounts WHERE company_id=?",company.value().toString())).isEqualTo(Long.MAX_VALUE);assertThat(number(db,"SELECT total_shares FROM companies WHERE id=?",company.value().toString())).isEqualTo(1000);assertThat(number(db,"SELECT COUNT(*) FROM share_holdings WHERE company_id=? AND holder_uuid=?",company.value().toString(),player.toString())).isZero();assertThat(number(db,"SELECT COUNT(*) FROM escrow_ledger_entries WHERE liability_kind='COMPANY_TREASURY' AND company_id=?",company.value().toString())).isZero();assertThat(number(db,"SELECT COUNT(*) FROM treasury_operations WHERE id=? AND state='ESCROW_DEPOSITED'",subscription.toString())).isEqualTo(1);}finally{Files.deleteIfExists(file);} }
 @Test void successful_expiry_creates_listing_updates_company_and_records_reference_audit() throws Exception { Path file=Files.createTempFile("ipo-listing-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var listings=new SqlStockListingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); completeSubscription(db,repo,offer,2); db.inTransaction(c->{repo.closeExpired(c,offer.closesAt());return null;}); assertThat(listings.findByCompany(company)).contains(new StockListing(company,"BS000001",offer.issuePrice(),1002,offer.closesAt())); assertThat(companyStatus(db,company)).isEqualTo(CompanyStatus.LISTED.name()); assertThat(auditJsonValue(db,"IPO_LISTED",offer.id(),"stockCode")).isEqualTo("BS000001"); assertThat(auditJsonValue(db,"IPO_LISTED",offer.id(),"issueReferencePriceMinor")).isEqualTo("10"); assertThat(auditJsonValue(db,"IPO_LISTED",offer.id(),"issuedShares")).isEqualTo("1002"); assertThat(auditJsonValue(db,"IPO_LISTED",offer.id(),"source")).isEqualTo("IPO_CLOSE"); assertThat(auditJsonValue(db,"IPO_LISTED",offer.id(),"actor")).isEmpty(); }finally{Files.deleteIfExists(file);} }
 @Test void sellout_close_creates_one_listing_audit_and_keeps_sequence_idempotent() throws Exception { Path file=Files.createTempFile("ipo-listing-sellout-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var listings=new SqlStockListingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); completeSubscription(db,repo,offer,10); db.inTransaction(c->{repo.closeExpired(c,offer.closesAt());return null;}); assertThat(repo.find(offer.id()).orElseThrow().state()).isEqualTo(cn.blockeco.exchange.domain.finance.PrimaryOfferingState.CLOSED); assertThat(listings.findByCompany(company)).contains(new StockListing(company,"BS000001",offer.issuePrice(),1010,offer.opensAt())); assertThat(companyStatus(db,company)).isEqualTo(CompanyStatus.LISTED.name()); assertThat(auditCount(db,"IPO_LISTED",offer.id())).isEqualTo(1); assertThat(sequenceValue(db)).isEqualTo(1); }finally{Files.deleteIfExists(file);} }
 @Test void exhausted_stock_code_sequence_rolls_back_offering_listing_status_and_audit() throws Exception { Path file=Files.createTempFile("ipo-listing-exhausted-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var listings=new SqlStockListingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); completeSubscription(db,repo,offer,2); db.inTransaction(c->{try(var s=c.prepareStatement("UPDATE stock_code_sequence SET last_value=999999 WHERE singleton=1")){s.executeUpdate();}return null;}); org.assertj.core.api.Assertions.assertThatThrownBy(()->db.inTransaction(c->{repo.closeExpired(c,offer.closesAt());return null;})).isInstanceOf(StockCodeExhaustedException.class).hasMessage("股票代码已分配完毕，IPO关闭未完成上市。"); assertThat(repo.find(offer.id()).orElseThrow().state()).isNotEqualTo(cn.blockeco.exchange.domain.finance.PrimaryOfferingState.CLOSED); assertThat(listings.findByCompany(company)).isEmpty(); assertThat(companyStatus(db,company)).isNotEqualTo(CompanyStatus.LISTED.name()); assertThat(auditCount(db,"IPO_LISTED",offer.id())).isZero(); }finally{Files.deleteIfExists(file);} }
 @Test void independent_sqlite_connections_allocate_unique_consecutive_stock_codes() throws Exception { Path file=Files.createTempFile("ipo-listing-concurrent-", ".db"); String jdbc="jdbc:sqlite:"+file; cn.blockeco.exchange.domain.finance.PrimaryOffering first; cn.blockeco.exchange.domain.finance.PrimaryOffering second; try(Database db=new Database(jdbc)){db.migrate(); var company=Fixtures.company(db,100); db.inTransaction(c->{try(var s=c.prepareStatement("UPDATE companies SET normalized_name='ipo test one', display_name='Ipo Test One' WHERE id=?")){s.setString(1,company.value().toString());s.executeUpdate();}return null;}); var companyTwo=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); first=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); second=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(companyTwo,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); completeSubscription(db,repo,first,2); completeSubscription(db,repo,second,3); } HikariConfig config=new HikariConfig(); config.setJdbcUrl(jdbc); config.setMaximumPoolSize(2); config.setConnectionInitSql("PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000"); try(HikariDataSource source=new HikariDataSource(config); ExecutorService executor=Executors.newFixedThreadPool(2)){var repo=new SqlPrimaryOfferingRepository(source); var listings=new SqlStockListingRepository(source); CountDownLatch ready=new CountDownLatch(2), start=new CountDownLatch(1); Future<?> one=executor.submit(()->closeOnIndependentConnection(source,repo,first,ready,start)); Future<?> two=executor.submit(()->closeOnIndependentConnection(source,repo,second,ready,start)); ready.await(); start.countDown(); one.get(); two.get(); assertThat(listings.findByCode("BS000001")).isPresent(); assertThat(listings.findByCode("BS000002")).isPresent(); }finally{Files.deleteIfExists(file);} }
 @Test void public_offerings_expose_only_safe_capacity_and_issued_share_projections() throws Exception { Path file=Files.createTempFile("ipo-public-view-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); UUID completed=UUID.randomUUID(),refunded=UUID.randomUUID(),ambiguous=UUID.randomUUID(); db.inTransaction(c->{repo.announce(c,offer);repo.closeExpired(c,offer.opensAt());repo.prepareSubscription(c,completed,offer,UUID.randomUUID(),2,offer.opensAt());repo.markWithdrawn(c,completed,offer.opensAt());repo.markEscrowDeposited(c,completed,offer.opensAt());repo.completeSubscription(c,completed,offer.opensAt());repo.prepareSubscription(c,refunded,offer,UUID.randomUUID(),3,offer.opensAt());repo.cancelPrepared(c,refunded,offer.opensAt());repo.prepareSubscription(c,ambiguous,offer,UUID.randomUUID(),1,offer.opensAt());repo.markAmbiguous(c,ambiguous,"WITHDRAW","timeout",offer.opensAt());return null;}); PublicOfferingView view=repo.findPublic(offer.id()).orElseThrow(); assertThat(view).extracting(PublicOfferingView::companyDisplayName,PublicOfferingView::target,PublicOfferingView::issuePrice,PublicOfferingView::maximumShares,PublicOfferingView::issuedShares,PublicOfferingView::reservedShares,PublicOfferingView::availableShares).containsExactly("Ipo Test",Money.ofMinor(100),Money.ofMinor(10),10L,2L,3L,7L); }finally{Files.deleteIfExists(file);} }
 @Test void public_offerings_are_newest_first_clamped_and_find_missing_is_empty() throws Exception { Path file=Files.createTempFile("ipo-public-order-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var oldOffer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); var newOffer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(200),Money.ofMinor(10),Instant.parse("2026-08-15T12:00:00Z")); db.inTransaction(c->{repo.announce(c,oldOffer);repo.announce(c,newOffer);return null;}); assertThat(repo.listPublic(0)).extracting(PublicOfferingView::offeringId).containsExactly(newOffer.id()); assertThat(repo.listPublic(100)).extracting(PublicOfferingView::offeringId).containsExactly(newOffer.id(),oldOffer.id()); assertThat(repo.findPublic(UUID.randomUUID())).isEmpty(); }finally{Files.deleteIfExists(file);} }
 @Test void overdue_scheduler_run_records_ordered_open_then_close_audits() throws Exception { Path file=Files.createTempFile("ipo-overdue-audit-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); db.inTransaction(c->{repo.announce(c,offer);repo.closeExpired(c,offer.closesAt());return null;}); assertThat(stateAuditCount(db,offer.id(),"OPEN")).isEqualTo(1); assertThat(stateAuditCount(db,offer.id(),"CLOSED")).isEqualTo(1); assertThat(repo.find(offer.id()).orElseThrow().state()).isEqualTo(cn.blockeco.exchange.domain.finance.PrimaryOfferingState.CLOSED); }finally{Files.deleteIfExists(file);} }
 @Test void scheduler_opening_appends_one_immutable_state_audit_with_scheduler_payload() throws Exception { Path file=Files.createTempFile("ipo-open-audit-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); db.inTransaction(c->{repo.announce(c,offer);repo.closeExpired(c,offer.opensAt());return null;}); assertThat(stateAuditCount(db,offer.id(),"OPEN")).isEqualTo(1); assertThat(auditPayload(db,"IPO_STATE_CHANGED",offer.id())).contains("offeringId","companyId","from","ANNOUNCED","to","OPEN","reason","OPEN_TIME","actor","source","SCHEDULER"); }finally{Files.deleteIfExists(file);} }
 @Test void scheduler_expiry_closes_once_with_audit_and_never_issues_unsold_shares() throws Exception { Path file=Files.createTempFile("ipo-close-audit-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); db.inTransaction(c->{repo.announce(c,offer);repo.closeExpired(c,offer.opensAt());repo.closeExpired(c,offer.closesAt());repo.closeExpired(c,offer.closesAt());return null;}); assertThat(stateAuditCount(db,offer.id(),"CLOSED")).isEqualTo(1); assertThat(auditPayload(db,"IPO_STATE_CHANGED",offer.id())).contains("from","OPEN","to","CLOSED","reason","EXPIRED","source","SCHEDULER"); assertThat(repo.companyTotalShares(company)).isEqualTo(1000); }finally{Files.deleteIfExists(file);} }
 @Test void close_expired_does_not_issue_unsold_shares_or_list_a_zero_subscription_offering() throws Exception { Path file=Files.createTempFile("ipo-sql-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); db.inTransaction(c->{repo.announce(c,offer);return null;}); db.inTransaction(c->{repo.closeExpired(c,offer.closesAt());return null;}); assertThat(repo.find(offer.id()).orElseThrow().state()).isEqualTo(cn.blockeco.exchange.domain.finance.PrimaryOfferingState.CLOSED); assertThat(repo.companyTotalShares(company)).isEqualTo(1000); assertThat(companyStatus(db,company)).isEqualTo("PENDING_ASSET_BINDING"); assertThat(auditCount(db,"IPO_LISTED",offer.id())).isZero(); }finally{Files.deleteIfExists(file);} }
 @Test void announcement_contains_discoverable_full_terms_and_no_return_promise() throws Exception { Path file=Files.createTempFile("ipo-announcement-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); db.inTransaction(c->{repo.announce(c,offer);return null;}); assertThat(announcement(db,offer.id())).contains(offer.id().toString(),"目标=100","发行价=10","最大股数=10",offer.opensAt().toString(),offer.closesAt().toString(),"实缴资本=100","风险提示").doesNotContain("保证收益"); }finally{Files.deleteIfExists(file);} }
 private static void completeSubscription(Database db,SqlPrimaryOfferingRepository repo,cn.blockeco.exchange.domain.finance.PrimaryOffering offer,long shares){ UUID subscription=UUID.randomUUID(); db.inTransaction(c->{repo.announce(c,offer);repo.prepareSubscription(c,subscription,offer,UUID.randomUUID(),shares,offer.opensAt());repo.markWithdrawn(c,subscription,offer.opensAt());repo.markEscrowDeposited(c,subscription,offer.opensAt());repo.completeSubscription(c,subscription,offer.opensAt());return null;}); }
 private static void closeOnIndependentConnection(HikariDataSource source,SqlPrimaryOfferingRepository repo,cn.blockeco.exchange.domain.finance.PrimaryOffering offer,CountDownLatch ready,CountDownLatch start){try{ready.countDown();start.await();for(int attempt=0;;attempt++){try(Connection connection=source.getConnection()){try(var statement=connection.createStatement()){statement.execute("PRAGMA busy_timeout=5000");}connection.setAutoCommit(false);repo.closeExpired(connection,offer.closesAt());connection.commit();return;}catch(java.sql.SQLException exception){if(attempt==4||!exception.getMessage().contains("locked"))throw exception;Thread.sleep(50L);}}}catch(Exception exception){throw new RuntimeException(exception);}}
 private static String announcement(Database db,java.util.UUID offering){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT body FROM company_announcements WHERE offering_id=?")){s.setString(1,offering.toString());try(var r=s.executeQuery()){r.next();return r.getString(1);}}catch(Exception e){throw new RuntimeException(e);}}
 private static String companyStatus(Database db,cn.blockeco.exchange.domain.company.CompanyId company){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT status FROM companies WHERE id=?")){s.setString(1,company.value().toString());try(var r=s.executeQuery()){r.next();return r.getString(1);}}catch(Exception e){throw new RuntimeException(e);}}
 private static long auditCount(Database db,String type,java.util.UUID offering){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT COUNT(*) FROM audit_events WHERE event_type=? AND payload_json LIKE ?")){s.setString(1,type);s.setString(2,"%"+offering+"%");try(var r=s.executeQuery()){r.next();return r.getLong(1);}}catch(Exception e){throw new RuntimeException(e);}}
 private static long stateAuditCount(Database db,java.util.UUID offering,String to){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT COUNT(*) FROM audit_events WHERE event_type='IPO_STATE_CHANGED' AND payload_json LIKE ? AND payload_json LIKE ?")){s.setString(1,"%"+offering+"%");s.setString(2,"%\"to\":\""+to+"\"%");try(var r=s.executeQuery()){r.next();return r.getLong(1);}}catch(Exception e){throw new RuntimeException(e);}}
 private static String auditPayload(Database db,String type,java.util.UUID offering){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT payload_json FROM audit_events WHERE event_type=? AND payload_json LIKE ? ORDER BY sequence DESC")){s.setString(1,type);s.setString(2,"%"+offering+"%");try(var r=s.executeQuery()){r.next();return r.getString(1);}}catch(Exception e){throw new RuntimeException(e);}}
 private static String auditJsonValue(Database db,String type,java.util.UUID offering,String field){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT json_extract(payload_json, ?) FROM audit_events WHERE event_type=? AND payload_json LIKE ? ORDER BY sequence DESC")){s.setString(1,"$."+field);s.setString(2,type);s.setString(3,"%"+offering+"%");try(var r=s.executeQuery()){r.next();return r.getString(1);}}catch(Exception e){throw new RuntimeException(e);}}
 private static long sequenceValue(Database db){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT last_value FROM stock_code_sequence WHERE singleton=1");var r=s.executeQuery()){r.next();return r.getLong(1);}catch(Exception e){throw new RuntimeException(e);}}
 private static long number(Database db,String sql,String... values){try(var c=db.dataSource().getConnection();var s=c.prepareStatement(sql)){for(int i=0;i<values.length;i++)s.setString(i+1,values[i]);try(var r=s.executeQuery()){r.next();return r.getLong(1);}}catch(Exception e){throw new RuntimeException(e);}}
}
