package cn.blockeco.exchange.infrastructure.sql;

import static org.assertj.core.api.Assertions.assertThat;
import cn.blockeco.exchange.application.Fixtures;
import cn.blockeco.exchange.domain.finance.PublicOfferingView;
import cn.blockeco.exchange.domain.money.Money;
import java.nio.file.*;
import java.time.Instant;
import java.util.UUID;
import org.junit.jupiter.api.Test;

class SqlPrimaryOfferingRepositoryTest {
 @Test void public_offerings_expose_only_safe_capacity_and_issued_share_projections() throws Exception { Path file=Files.createTempFile("ipo-public-view-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); UUID completed=UUID.randomUUID(),refunded=UUID.randomUUID(),ambiguous=UUID.randomUUID(); db.inTransaction(c->{repo.announce(c,offer);repo.closeExpired(c,offer.opensAt());repo.prepareSubscription(c,completed,offer,UUID.randomUUID(),2,offer.opensAt());repo.markWithdrawn(c,completed,offer.opensAt());repo.markEscrowDeposited(c,completed,offer.opensAt());repo.completeSubscription(c,completed,offer.opensAt());repo.prepareSubscription(c,refunded,offer,UUID.randomUUID(),3,offer.opensAt());repo.cancelPrepared(c,refunded,offer.opensAt());repo.prepareSubscription(c,ambiguous,offer,UUID.randomUUID(),1,offer.opensAt());repo.markAmbiguous(c,ambiguous,"WITHDRAW","timeout",offer.opensAt());return null;}); PublicOfferingView view=repo.findPublic(offer.id()).orElseThrow(); assertThat(view).extracting(PublicOfferingView::companyDisplayName,PublicOfferingView::target,PublicOfferingView::issuePrice,PublicOfferingView::maximumShares,PublicOfferingView::issuedShares,PublicOfferingView::reservedShares,PublicOfferingView::availableShares).containsExactly("Ipo Test",Money.ofMinor(100),Money.ofMinor(10),10L,2L,3L,7L); }finally{Files.deleteIfExists(file);} }
 @Test void public_offerings_are_newest_first_clamped_and_find_missing_is_empty() throws Exception { Path file=Files.createTempFile("ipo-public-order-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var oldOffer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); var newOffer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(200),Money.ofMinor(10),Instant.parse("2026-08-15T12:00:00Z")); db.inTransaction(c->{repo.announce(c,oldOffer);repo.announce(c,newOffer);return null;}); assertThat(repo.listPublic(0)).extracting(PublicOfferingView::offeringId).containsExactly(newOffer.id()); assertThat(repo.listPublic(100)).extracting(PublicOfferingView::offeringId).containsExactly(newOffer.id(),oldOffer.id()); assertThat(repo.findPublic(UUID.randomUUID())).isEmpty(); }finally{Files.deleteIfExists(file);} }
 @Test void overdue_scheduler_run_records_ordered_open_then_close_audits() throws Exception { Path file=Files.createTempFile("ipo-overdue-audit-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); db.inTransaction(c->{repo.announce(c,offer);repo.closeExpired(c,offer.closesAt());return null;}); assertThat(stateAuditCount(db,offer.id(),"OPEN")).isEqualTo(1); assertThat(stateAuditCount(db,offer.id(),"CLOSED")).isEqualTo(1); assertThat(repo.find(offer.id()).orElseThrow().state()).isEqualTo(cn.blockeco.exchange.domain.finance.PrimaryOfferingState.CLOSED); }finally{Files.deleteIfExists(file);} }
 @Test void scheduler_opening_appends_one_immutable_state_audit_with_scheduler_payload() throws Exception { Path file=Files.createTempFile("ipo-open-audit-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); db.inTransaction(c->{repo.announce(c,offer);repo.closeExpired(c,offer.opensAt());return null;}); assertThat(stateAuditCount(db,offer.id(),"OPEN")).isEqualTo(1); assertThat(auditPayload(db,"IPO_STATE_CHANGED",offer.id())).contains("offeringId","companyId","from","ANNOUNCED","to","OPEN","reason","OPEN_TIME","actor","source","SCHEDULER"); }finally{Files.deleteIfExists(file);} }
 @Test void scheduler_expiry_closes_once_with_audit_and_never_issues_unsold_shares() throws Exception { Path file=Files.createTempFile("ipo-close-audit-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); db.inTransaction(c->{repo.announce(c,offer);repo.closeExpired(c,offer.opensAt());repo.closeExpired(c,offer.closesAt());repo.closeExpired(c,offer.closesAt());return null;}); assertThat(stateAuditCount(db,offer.id(),"CLOSED")).isEqualTo(1); assertThat(auditPayload(db,"IPO_STATE_CHANGED",offer.id())).contains("from","OPEN","to","CLOSED","reason","EXPIRED","source","SCHEDULER"); assertThat(repo.companyTotalShares(company)).isEqualTo(1000); }finally{Files.deleteIfExists(file);} }
 @Test void close_expired_does_not_issue_unsold_shares_or_list_a_zero_subscription_offering() throws Exception { Path file=Files.createTempFile("ipo-sql-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); db.inTransaction(c->{repo.announce(c,offer);return null;}); db.inTransaction(c->{repo.closeExpired(c,offer.closesAt());return null;}); assertThat(repo.find(offer.id()).orElseThrow().state()).isEqualTo(cn.blockeco.exchange.domain.finance.PrimaryOfferingState.CLOSED); assertThat(repo.companyTotalShares(company)).isEqualTo(1000); assertThat(companyStatus(db,company)).isEqualTo("PENDING_ASSET_BINDING"); assertThat(auditCount(db,"IPO_LISTED",offer.id())).isZero(); }finally{Files.deleteIfExists(file);} }
 @Test void announcement_contains_discoverable_full_terms_and_no_return_promise() throws Exception { Path file=Files.createTempFile("ipo-announcement-", ".db"); try(Database db=new Database("jdbc:sqlite:"+file)){db.migrate(); var company=Fixtures.company(db,100); var repo=new SqlPrimaryOfferingRepository(db.dataSource()); var offer=cn.blockeco.exchange.domain.finance.PrimaryOffering.plan(company,Money.ofMinor(100),Money.ofMinor(10),Instant.parse("2026-08-14T12:00:00Z")); db.inTransaction(c->{repo.announce(c,offer);return null;}); assertThat(announcement(db,offer.id())).contains(offer.id().toString(),"目标=100","发行价=10","最大股数=10",offer.opensAt().toString(),offer.closesAt().toString(),"实缴资本=100","风险提示").doesNotContain("保证收益"); }finally{Files.deleteIfExists(file);} }
 private static String announcement(Database db,java.util.UUID offering){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT body FROM company_announcements WHERE offering_id=?")){s.setString(1,offering.toString());try(var r=s.executeQuery()){r.next();return r.getString(1);}}catch(Exception e){throw new RuntimeException(e);}}
 private static String companyStatus(Database db,cn.blockeco.exchange.domain.company.CompanyId company){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT status FROM companies WHERE id=?")){s.setString(1,company.value().toString());try(var r=s.executeQuery()){r.next();return r.getString(1);}}catch(Exception e){throw new RuntimeException(e);}}
 private static long auditCount(Database db,String type,java.util.UUID offering){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT COUNT(*) FROM audit_events WHERE event_type=? AND payload_json LIKE ?")){s.setString(1,type);s.setString(2,"%"+offering+"%");try(var r=s.executeQuery()){r.next();return r.getLong(1);}}catch(Exception e){throw new RuntimeException(e);}}
 private static long stateAuditCount(Database db,java.util.UUID offering,String to){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT COUNT(*) FROM audit_events WHERE event_type='IPO_STATE_CHANGED' AND payload_json LIKE ? AND payload_json LIKE ?")){s.setString(1,"%"+offering+"%");s.setString(2,"%\"to\":\""+to+"\"%");try(var r=s.executeQuery()){r.next();return r.getLong(1);}}catch(Exception e){throw new RuntimeException(e);}}
 private static String auditPayload(Database db,String type,java.util.UUID offering){try(var c=db.dataSource().getConnection();var s=c.prepareStatement("SELECT payload_json FROM audit_events WHERE event_type=? AND payload_json LIKE ? ORDER BY sequence DESC")){s.setString(1,type);s.setString(2,"%"+offering+"%");try(var r=s.executeQuery()){r.next();return r.getString(1);}}catch(Exception e){throw new RuntimeException(e);}}
}
